/-
Copyright (c) 2026 Igor Zubrycki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Igor Zubrycki
-/
import DynamicalSystems.OptimalControl.ContinuousTime.TimeReparametrizationFamily
import Mathlib.Analysis.Calculus.Deriv.Shift

/-!
# Finite piecewise C1 competitors and optimal subarcs

The admissible class is generated by C1 arcs and finitely many continuous joins.
Its definition contains no variational identities or necessary optimality conditions.
Splitting and replacing an arc therefore permits additional corners.
-/

open MeasureTheory Set Filter
open scoped Topology Interval

namespace FinitePiecewise

open TimeReparametrization

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- A positive-duration curve assembled from finitely many C1 arcs with matching joins. -/
inductive IsFinitePiecewiseC1 : ℝ → (ℝ → E) → Prop
  | smooth {T : ℝ} {x v : ℝ → E} (hT : 0 < T)
      (hx : ∀ t, HasDerivAt x (v t) t) (hv : Continuous v) :
      IsFinitePiecewiseC1 T x
  | join {d₁ d₂ : ℝ} {x₁ x₂ : ℝ → E}
      (h₁ : IsFinitePiecewiseC1 d₁ x₁) (h₂ : IsFinitePiecewiseC1 d₂ x₂)
      (hjoin : x₁ d₁ = x₂ 0) :
      IsFinitePiecewiseC1 (d₁ + d₂) (concatenate d₁ x₁ x₂)

/-- The finite-piecewise class with the original prescribed endpoints. -/
def fixedEndpointFinitePiecewiseC1Curves (T : ℝ) (a b : E) : Set (ℝ → E) :=
  {x | x 0 = a ∧ x T = b ∧ IsFinitePiecewiseC1 T x}

/-- The integral part of the original autonomous variational functional. -/
noncomputable def action (L : E → E → ℝ) (T : ℝ) (x : ℝ → E) : ℝ :=
  ∫ t in 0..T, L (x t) (deriv x t)

theorem IsFinitePiecewiseC1.duration_pos {T : ℝ} {x : ℝ → E}
    (hx : IsFinitePiecewiseC1 T x) : 0 < T := by
  induction hx with
  | smooth hT _ _ => exact hT
  | join _ _ _ h₁ h₂ => exact add_pos h₁ h₂

theorem IsFinitePiecewiseC1.continuous {T : ℝ} {x : ℝ → E}
    (hx : IsFinitePiecewiseC1 T x) : Continuous x := by
  induction hx with
  | smooth _ h _ => exact continuous_iff_continuousAt.mpr fun t ↦ (h t).continuousAt
  | join _ _ hj h₁ h₂ => exact concatenate_continuous h₁ h₂ hj

private theorem density_concatenate_left (L : E → E → ℝ)
    {s t : ℝ} {x₁ x₂ : ℝ → E} (ht : t < s) :
    L (concatenate s x₁ x₂ t) (deriv (concatenate s x₁ x₂) t) =
      L (x₁ t) (deriv x₁ t) := by
  have he : concatenate s x₁ x₂ =ᶠ[𝓝 t] x₁ := by
    filter_upwards [Iio_mem_nhds ht] with q hq
    simp [concatenate, (show q < s from hq).le]
  rw [he.deriv_eq]
  simp [concatenate, ht.le]

private theorem density_concatenate_right (L : E → E → ℝ)
    {s t : ℝ} {x₁ x₂ : ℝ → E} (ht : s < t) :
    L (concatenate s x₁ x₂ t) (deriv (concatenate s x₁ x₂) t) =
      L (x₂ (t - s)) (deriv x₂ (t - s)) := by
  have he : concatenate s x₁ x₂ =ᶠ[𝓝 t] fun q ↦ x₂ (q - s) := by
    filter_upwards [Ioi_mem_nhds ht] with q hq
    simp [concatenate, not_le_of_gt (show s < q from hq)]
  rw [he.deriv_eq, deriv_comp_sub_const]
  simp [concatenate, not_le_of_gt ht]

private theorem integrable_concatenate_parts (L : E → E → ℝ)
    {d₁ d₂ : ℝ} (hd₁ : 0 < d₁) (hd₂ : 0 < d₂) {x₁ x₂ : ℝ → E}
    (hi₁ : IntervalIntegrable (fun t ↦ L (x₁ t) (deriv x₁ t)) volume 0 d₁)
    (hi₂ : IntervalIntegrable (fun t ↦ L (x₂ t) (deriv x₂ t)) volume 0 d₂) :
    IntervalIntegrable (fun t ↦ L (concatenate d₁ x₁ x₂ t)
      (deriv (concatenate d₁ x₁ x₂) t)) volume 0 d₁ ∧
    IntervalIntegrable (fun t ↦ L (concatenate d₁ x₁ x₂ t)
      (deriv (concatenate d₁ x₁ x₂) t)) volume d₁ (d₁ + d₂) := by
  constructor
  · apply hi₁.congr_uIoo
    intro t ht
    symm
    exact density_concatenate_left L (show t < d₁ from
      (show t ∈ Ioo 0 d₁ by simpa [uIoo_of_le hd₁.le] using ht).2)
  · have hi := hi₂.comp_sub_right d₁
    have hi' : IntervalIntegrable
        (fun t ↦ L (x₂ (t - d₁)) (deriv x₂ (t - d₁))) volume d₁ (d₁ + d₂) := by
      simpa only [zero_add, add_comm d₂ d₁] using hi
    apply hi'.congr_uIoo
    intro t ht
    symm
    exact density_concatenate_right L (show d₁ < t from
      (show t ∈ Ioo d₁ (d₁ + d₂) by
        simpa [uIoo_of_le (le_add_of_nonneg_right hd₂.le)] using ht).1)

theorem IsFinitePiecewiseC1.intervalIntegrable (L : E → E → ℝ)
    (hL : Continuous L.uncurry) {T : ℝ} {x : ℝ → E}
    (hx : IsFinitePiecewiseC1 T x) :
    IntervalIntegrable (fun t ↦ L (x t) (deriv x t)) volume 0 T := by
  induction hx with
  | @smooth T x v hT hx hv =>
    have hc : Continuous x := continuous_iff_continuousAt.mpr fun t ↦ (hx t).continuousAt
    simpa only [funext (fun t ↦ (hx t).deriv), Function.comp_def, Function.uncurry] using
      (hL.comp (hc.prodMk hv)).intervalIntegrable 0 _
  | join h₁ h₂ hj hi₁ hi₂ =>
    have hi := integrable_concatenate_parts L h₁.duration_pos h₂.duration_pos hi₁ hi₂
    exact hi.1.trans hi.2

theorem action_concatenate (L : E → E → ℝ) (hL : Continuous L.uncurry)
    {d₁ d₂ : ℝ} {x₁ x₂ : ℝ → E}
    (h₁ : IsFinitePiecewiseC1 d₁ x₁) (h₂ : IsFinitePiecewiseC1 d₂ x₂) :
    action L (d₁ + d₂) (concatenate d₁ x₁ x₂) =
      action L d₁ x₁ + action L d₂ x₂ := by
  have hi := integrable_concatenate_parts L h₁.duration_pos h₂.duration_pos
    (h₁.intervalIntegrable L hL) (h₂.intervalIntegrable L hL)
  unfold action
  rw [← intervalIntegral.integral_add_adjacent_intervals hi.1 hi.2]
  congr 1
  · apply intervalIntegral.integral_congr_Ioo_of_le h₁.duration_pos.le
    intro t ht
    exact density_concatenate_left L ht.2
  · calc
      _ = ∫ t in d₁..d₁ + d₂, L (x₂ (t - d₁)) (deriv x₂ (t - d₁)) := by
        apply intervalIntegral.integral_congr_Ioo_of_le
          (le_add_of_nonneg_right h₂.duration_pos.le)
        intro t ht
        exact density_concatenate_right L ht.1
      _ = _ := by
        simpa only [sub_self, add_sub_cancel_left] using
          intervalIntegral.integral_comp_sub_right
            (fun t ↦ L (x₂ t) (deriv x₂ t)) (a := d₁) (b := d₁ + d₂) d₁

theorem concatenate_mem_fixedEndpointFinitePiecewiseC1Curves
    {d₁ d₂ : ℝ} {x₁ x₂ : ℝ → E}
    (h₁ : IsFinitePiecewiseC1 d₁ x₁) (h₂ : IsFinitePiecewiseC1 d₂ x₂)
    (hjoin : x₁ d₁ = x₂ 0) :
    concatenate d₁ x₁ x₂ ∈
      fixedEndpointFinitePiecewiseC1Curves (d₁ + d₂) (x₁ 0) (x₂ d₂) := by
  refine ⟨?_, ?_, .join h₁ h₂ hjoin⟩
  · simp [concatenate, h₁.duration_pos.le]
  · simp [concatenate, not_le_of_gt (lt_add_of_pos_right d₁ h₂.duration_pos)]

theorem action_min_of_cvFunctional_min (L : E → E → ℝ) (K : E → ℝ)
    {T : ℝ} {a b : E} {x : ℝ → E} (hx : x T = b)
    (hmin : IsMinOn (cvFunctional (fun _ ↦ L) K T)
      (fixedEndpointFinitePiecewiseC1Curves T a b) x) :
    IsMinOn (action L T) (fixedEndpointFinitePiecewiseC1Curves T a b) x := by
  intro y hy
  have h := hmin hy
  change action L T x + K (x T) ≤ action L T y + K (y T) at h
  rw [hx, hy.2.1] at h
  exact (add_le_add_iff_right _).mp h

theorem cvFunctional_min_of_action_min (L : E → E → ℝ) (K : E → ℝ)
    {T : ℝ} {a b : E} {x : ℝ → E} (hx : x T = b)
    (hmin : IsMinOn (action L T) (fixedEndpointFinitePiecewiseC1Curves T a b) x) :
    IsMinOn (cvFunctional (fun _ ↦ L) K T)
      (fixedEndpointFinitePiecewiseC1Curves T a b) x := by
  intro y hy
  change action L T x + K (x T) ≤ action L T y + K (y T)
  rw [hx, hy.2.1]
  have h : action L T x ≤ action L T y := hmin hy
  linarith

/-- Replacing the left subarc by any finite-piecewise competitor is feasible and
preserves the right cost. Thus ambient optimality implies left-subarc optimality. -/
theorem action_min_left (L : E → E → ℝ) (hL : Continuous L.uncurry)
    {d₁ d₂ : ℝ} {x₁ x₂ : ℝ → E}
    (h₁ : IsFinitePiecewiseC1 d₁ x₁) (h₂ : IsFinitePiecewiseC1 d₂ x₂)
    (hjoin : x₁ d₁ = x₂ 0)
    (hmin : IsMinOn (action L (d₁ + d₂))
      (fixedEndpointFinitePiecewiseC1Curves (d₁ + d₂) (x₁ 0) (x₂ d₂))
      (concatenate d₁ x₁ x₂)) :
    IsMinOn (action L d₁) (fixedEndpointFinitePiecewiseC1Curves d₁ (x₁ 0) (x₁ d₁)) x₁ := by
  intro y hy
  have hj : y d₁ = x₂ 0 := hy.2.1.trans hjoin
  have hm := concatenate_mem_fixedEndpointFinitePiecewiseC1Curves hy.2.2 h₂ hj
  rw [hy.1] at hm
  have h := hmin hm
  change action L (d₁ + d₂) (concatenate d₁ x₁ x₂) ≤
    action L (d₁ + d₂) (concatenate d₁ y x₂) at h
  rw [action_concatenate L hL h₁ h₂, action_concatenate L hL hy.2.2 h₂] at h
  exact (add_le_add_iff_right _).mp h

/-- The same actual splice argument for the right subarc. -/
theorem action_min_right (L : E → E → ℝ) (hL : Continuous L.uncurry)
    {d₁ d₂ : ℝ} {x₁ x₂ : ℝ → E}
    (h₁ : IsFinitePiecewiseC1 d₁ x₁) (h₂ : IsFinitePiecewiseC1 d₂ x₂)
    (hjoin : x₁ d₁ = x₂ 0)
    (hmin : IsMinOn (action L (d₁ + d₂))
      (fixedEndpointFinitePiecewiseC1Curves (d₁ + d₂) (x₁ 0) (x₂ d₂))
      (concatenate d₁ x₁ x₂)) :
    IsMinOn (action L d₂) (fixedEndpointFinitePiecewiseC1Curves d₂ (x₂ 0) (x₂ d₂)) x₂ := by
  intro y hy
  have hj : x₁ d₁ = y 0 := hjoin.trans hy.1.symm
  have hm := concatenate_mem_fixedEndpointFinitePiecewiseC1Curves h₁ hy.2.2 hj
  rw [hy.2.1] at hm
  have h := hmin hm
  change action L (d₁ + d₂) (concatenate d₁ x₁ x₂) ≤
    action L (d₁ + d₂) (concatenate d₁ x₁ y) at h
  rw [action_concatenate L hL h₁ h₂, action_concatenate L hL h₁ hy.2.2] at h
  exact (add_le_add_iff_left _).mp h

/-- A finite surrounding context built by adjoining finite-piecewise prefix or suffix
arcs. Its hole has prescribed duration and endpoints; no optimality is encoded. -/
inductive SpliceContext (d : ℝ) (a b : E) :
    ℝ → E → E → ((ℝ → E) → ℝ → E) → Prop
  | hole : SpliceContext d a b d a b id
  | append {T s : ℝ} {A B : E} {F : (ℝ → E) → ℝ → E} {z : ℝ → E}
      (ctx : SpliceContext d a b T A B F) (hz : IsFinitePiecewiseC1 s z)
      (hj : B = z 0) :
      SpliceContext d a b (T + s) A (z s) (fun y ↦ concatenate T (F y) z)
  | prepend {T s : ℝ} {A B : E} {F : (ℝ → E) → ℝ → E} {z : ℝ → E}
      (ctx : SpliceContext d a b T A B F) (hz : IsFinitePiecewiseC1 s z)
      (hj : z s = A) :
      SpliceContext d a b (s + T) (z 0) B (fun y ↦ concatenate s z (F y))

theorem SpliceContext.feasible {d T : ℝ} {a b A B : E}
    {F : (ℝ → E) → ℝ → E} (ctx : SpliceContext d a b T A B F)
    {x : ℝ → E} (hx : x ∈ fixedEndpointFinitePiecewiseC1Curves d a b) :
    F x ∈ fixedEndpointFinitePiecewiseC1Curves T A B := by
  induction ctx with
  | hole => exact hx
  | append ctx hz hj ih =>
    have h := concatenate_mem_fixedEndpointFinitePiecewiseC1Curves ih.2.2 hz
      (ih.2.1.trans hj)
    simpa only [ih.1] using h
  | prepend ctx hz hj ih =>
    have h := concatenate_mem_fixedEndpointFinitePiecewiseC1Curves hz ih.2.2
      (hj.trans ih.1.symm)
    simpa only [ih.2.1] using h

/-- Ambient minimum passes through any finite surrounding context to its actual hole. -/
theorem SpliceContext.action_min (L : E → E → ℝ) (hL : Continuous L.uncurry)
    {d T : ℝ} {a b A B : E} {F : (ℝ → E) → ℝ → E}
    (ctx : SpliceContext d a b T A B F)
    {x : ℝ → E} (hx : x ∈ fixedEndpointFinitePiecewiseC1Curves d a b)
    (hmin : IsMinOn (action L T) (fixedEndpointFinitePiecewiseC1Curves T A B) (F x)) :
    IsMinOn (action L d) (fixedEndpointFinitePiecewiseC1Curves d a b) x := by
  induction ctx with
  | hole => exact hmin
  | append ctx hz hj ih =>
    have hf := ctx.feasible hx
    have hm : IsMinOn _ (fixedEndpointFinitePiecewiseC1Curves _ _ _) _ := hmin
    rw [← hf.1] at hm
    have hh := action_min_left L hL hf.2.2 hz (hf.2.1.trans hj) hm
    rw [hf.1, hf.2.1] at hh
    exact ih hh
  | prepend ctx hz hj ih =>
    have hf := ctx.feasible hx
    have hm : IsMinOn _ (fixedEndpointFinitePiecewiseC1Curves _ _ _) _ := hmin
    rw [← hf.2.1] at hm
    have hh := action_min_right L hL hz hf.2.2 (hj.trans hf.1.symm) hm
    rw [hf.1, hf.2.1] at hh
    exact ih hh

/-- Every physical duration exchange belongs to the finite-piecewise ambient class. -/
theorem durationExchange_mem_fixedEndpointFinitePiecewiseC1Curves
    {x₁ v₁ x₂ v₂ : ℝ → E}
    (hx₁ : ∀ t, HasDerivAt x₁ (v₁ t) t) (hv₁ : Continuous v₁)
    (hx₂ : ∀ t, HasDerivAt x₂ (v₂ t) t) (hv₂ : Continuous v₂)
    {d₁ d₂ ε : ℝ} (hd₁ : 0 < d₁) (hd₂ : 0 < d₂)
    (hjoin : x₁ d₁ = x₂ 0) (hε : ε ∈ Ioo (-d₁) d₂) :
    durationExchange x₁ x₂ d₁ d₂ ε ∈
      fixedEndpointFinitePiecewiseC1Curves (d₁ + d₂) (x₁ 0) (x₂ d₂) := by
  have he := durationExchange_endpoints x₁ x₂ hd₁ hd₂ hε
  refine ⟨he.1, he.2, ?_⟩
  have hp := rescaling_factors_pos hd₁ hd₂ hε
  have hd := exchanged_durations (ne_of_gt hd₁) (ne_of_gt hd₂) ε
  have h₁ : IsFinitePiecewiseC1 (d₁ + ε) (fun t ↦ x₁ (t / (1 + ε / d₁))) :=
    .smooth (by linarith [hε.1]) (hasDerivAt_rescaledArc hx₁ _)
      (continuous_const.smul (hv₁.comp (continuous_id.div_const _)))
  have h₂ : IsFinitePiecewiseC1 (d₂ - ε) (fun t ↦ x₂ (t / (1 - ε / d₂))) :=
    .smooth (by linarith [hε.2]) (hasDerivAt_rescaledArc hx₂ _)
      (continuous_const.smul (hv₂.comp (continuous_id.div_const _)))
  have hj : x₁ ((d₁ + ε) / (1 + ε / d₁)) = x₂ (0 / (1 - ε / d₂)) := by
    rw [← hd.1]
    simpa only [mul_div_cancel_left₀ d₁ (ne_of_gt hp.1), zero_div] using hjoin
  have h := IsFinitePiecewiseC1.join h₁ h₂ hj
  have ht : (d₁ + ε) + (d₂ - ε) = d₁ + d₂ := by ring
  simpa only [ht, durationExchange] using h

end FinitePiecewise
