import DynamicalSystems.OptimalControl.ContinuousTime.NeedlePMPOnHorizon

/-!
# Finite-horizon assumptions allow unbounded time dependence

The nonautonomous dynamics `x' = t + u` on `[0,1]` satisfy every primitive
finite-horizon hypothesis. The nominal field at state zero is `t - 1`, which
has no bound over all real times. This checks that the clamping wrapper removes
the old global bound-at-zero restriction rather than merely restating it.
-/

namespace K1HorizonRegression

open Set
open scoped NNReal

/-- A smooth nonautonomous integrator with unbounded temporal forcing. -/
def problem : ContinuousOCP ℝ ℝ where
  T := 1
  f := fun t _ u => t + u
  L := fun _ _ _ => 0
  K := fun _ => 0
  controlSet := Icc (-1) 1

/-- The trajectory generated by the constant control `-1` from state zero. -/
noncomputable def referenceState (t : ℝ) : ℝ := t ^ 2 / 2 - t
/-- A feasible constant control whose nominal zero-state forcing is unbounded in time. -/
def referenceControl (_ : ℝ) : ℝ := -1

/-- The complete compact-time analytic contract is satisfied. -/
noncomputable def regularity :
    K1NeedlePMPOnHorizon.SmoothNeedleDataOnHorizon
      problem referenceState referenceControl where
  horizon_pos := by norm_num [problem]
  nominal_lipschitz := ⟨0, fun t _ => LipschitzWith.const (t + -1)⟩
  test_lipschitz := fun v _ => ⟨0, fun t _ => LipschitzWith.const (t + v)⟩
  nominal_dynamics_continuous := (continuous_fst.add continuous_const).continuousOn
  test_dynamics_continuous := fun _ _ => (continuous_fst.add continuous_const).continuousOn
  nominal_running_continuous := continuous_const.continuousOn
  test_running_continuous := fun _ _ => continuous_const.continuousOn
  dynamicsDerivative := fun _ _ => 0
  has_dynamics_derivative := fun t _ y => hasFDerivAt_const (t + -1) y
  dynamics_derivative_continuous := continuous_const.continuousOn
  runningDerivative := fun _ _ => 0
  has_running_derivative := fun _ _ y => hasFDerivAt_const 0 y
  running_derivative_continuous := continuous_const.continuousOn
  terminal_differentiable := differentiableAt_const 0

/-- No all-real-time bound at the nominal zero state can hold. -/
theorem no_global_nominal_zero_bound :
    ¬ ∃ B : ℝ, ∀ t : ℝ, ‖problem.f t 0 (referenceControl t)‖ ≤ B := by
  rintro ⟨B, hB⟩
  have h := hB (B + 2)
  simp only [problem, referenceControl, Real.norm_eq_abs] at h
  have hlower := le_abs_self (B + 2 + -1)
  linarith

end K1HorizonRegression
