/-
Copyright (c) 2026 Igor Zubrycki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Igor Zubrycki
-/
module

public import Mathlib.Algebra.BigOperators.Fin
public import Mathlib.Basic.Real.Basic
public import Mathlib.Data.Set.Basic

/-! # Finite-horizon optimal control

This file sets up the purely set-theoretic data of a finite-horizon deterministic
optimal control problem and its trajectory/cost bookkeeping.  Nothing here uses
topological or vector-space structure: the state and input spaces are arbitrary
types, the dynamics is a bare transition map `f : X → U → X`, the stage and
terminal costs are functions into `ℝ`, and the state/input/terminal constraints
are plain sets.  This is the generic substrate on which the dynamic-programming
value function and the model predictive control layer are later built.

The definitions follow Rawlings, Mayne and Diehl, *Model Predictive Control:
Theory, Computation, and Design*, 2nd ed., 2019, Chapter 1, §1.3
(printed pp. 11–25) for the finite-horizon trajectory and cost, and Chapter 2,
§2.2 (printed p. 91) for the constraint sets `X`, `U` and the terminal set.

## Main definitions

* `FiniteHorizonProblem`: dynamics, stage cost, terminal cost, horizon and the
  state/input/terminal constraint sets.
* `finiteHorizonRollout`: the closed-loop trajectory `x(k)` generated by an input
  sequence `u : Fin N → U`.
* `finiteHorizonTotalCost`: `∑_{k<N} ℓ(x(k), u(k)) + Vf(x(N))`.
* `FiniteHorizonAdmissible`: the state/input/terminal constraint predicate.
* `FiniteHorizonFeasible`: existence of an admissible input sequence.

## Main results

* `finiteHorizonRollout_zero`: the trajectory starts at `x₀`.
* `finiteHorizonRollout_succ`: the one-step recursion defining the trajectory.
* `finiteHorizonTotalCost_zero`: with horizon `0` the total cost is `Vf x₀`.
* `finiteHorizonRollout_snoc`, `finiteHorizonRollout_snoc_last`,
  `finiteHorizonAdmissible_snoc`: rollout and admissibility bookkeeping for
  extending an input sequence by one terminal control.
* `totalCost_snoc`, `totalCost_succ_split`: finite-horizon cost splitting and
  shift identities.
-/

@[expose] public section

variable {X U : Type*}

/-- A finite-horizon deterministic optimal control problem.

The transition map is `f`, the stage cost is `stageCost`, the terminal cost is
`terminalCost`, the horizon is `horizon` (the number of control steps, so the
trajectory has `horizon + 1` states), and the constraints are the sets
`stateSet`, `inputSet` and `terminalSet` (Rawlings–Mayne–Diehl 2019, Ch. 1
§1.3 and Ch. 2 §2.2). -/
structure FiniteHorizonProblem (X U : Type*) where
  /-- The transition map `x⁺ = f x u`. -/
  (f : X → U → X)
  /-- The stage cost `ℓ x u`. -/
  (stageCost : X → U → ℝ)
  /-- The terminal cost `Vf x`. -/
  (terminalCost : X → ℝ)
  /-- The number of control steps (the trajectory has `horizon + 1` states). -/
  (horizon : ℕ)
  /-- The admissible state set `X`. -/
  (stateSet : Set X)
  /-- The admissible input set `U`. -/
  (inputSet : Set U)
  /-- The terminal constraint set `Xf`. -/
  (terminalSet : Set X)

/-- The closed-loop trajectory of `prob` from `x₀` under the input sequence `u`.

Index `0` is the initial state `x₀` and index `k + 1` is obtained by applying the
dynamics to the state at index `k` with the input `u k`.  This is
`Fin.induction` over the state index domain `Fin (horizon + 1)`. -/
def finiteHorizonRollout (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) : Fin (prob.horizon + 1) → X :=
  Fin.induction x₀ fun k xk => prob.f xk (u k)

/-- The finite-horizon total cost of the input sequence `u` from `x₀`:
the sum of the stage costs along the trajectory plus the terminal cost at the
final state (Rawlings–Mayne–Diehl 2019, Ch. 1 §1.3, printed p. 11). -/
def finiteHorizonTotalCost (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) : ℝ :=
  (∑ k : Fin prob.horizon,
      prob.stageCost (finiteHorizonRollout prob x₀ u k.castSucc) (u k)) +
    prob.terminalCost (finiteHorizonRollout prob x₀ u (Fin.last prob.horizon))

/-- Admissibility of an input sequence: every state `x(k)` for `k < horizon`
lies in `stateSet`, every input `u(k)` lies in `inputSet`, and the terminal state
`x(horizon)` lies in `terminalSet` (Rawlings–Mayne–Diehl 2019, Ch. 2 §2.2,
printed p. 91). -/
def FiniteHorizonAdmissible (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) : Prop :=
  (∀ k : Fin prob.horizon,
      finiteHorizonRollout prob x₀ u k.castSucc ∈ prob.stateSet ∧
        u k ∈ prob.inputSet) ∧
    finiteHorizonRollout prob x₀ u (Fin.last prob.horizon) ∈ prob.terminalSet

/-- Feasibility of a finite-horizon problem from `x₀`: there exists an admissible
input sequence. -/
def FiniteHorizonFeasible (prob : FiniteHorizonProblem X U) (x₀ : X) : Prop :=
  ∃ u, FiniteHorizonAdmissible prob x₀ u

/-- The trajectory at index `0` is the initial state. -/
@[simp]
theorem finiteHorizonRollout_zero (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) : finiteHorizonRollout prob x₀ u 0 = x₀ := by
  unfold finiteHorizonRollout
  rfl

/-- The one-step recursion defining the trajectory: the state at index `k + 1` is
the image under `f` of the state at index `k` with input `u k`. -/
@[simp]
theorem finiteHorizonRollout_succ (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) (k : Fin prob.horizon) :
    finiteHorizonRollout prob x₀ u (Fin.succ k) =
      prob.f (finiteHorizonRollout prob x₀ u k.castSucc) (u k) := by
  unfold finiteHorizonRollout
  exact Fin.induction_succ (motive := fun _ => X) x₀ (fun k xk => prob.f xk (u k)) k

/-- With horizon `0` there are no stage costs and the trajectory consists only of
the initial state, so the total cost is the terminal cost `Vf x₀`. -/
@[simp]
theorem finiteHorizonTotalCost_zero (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) (h : prob.horizon = 0) :
    finiteHorizonTotalCost prob x₀ u = prob.terminalCost x₀ := by
  obtain ⟨f, ℓ, Vf, N, Xs, Us, Xf⟩ := prob
  subst h
  simp [finiteHorizonTotalCost, finiteHorizonRollout]

/-- Extending an input sequence by one terminal stabilizing control shifts the
rollout of the successor state: for `v = Fin.snoc (Fin.tail u) w` started at
`f x₀ (u 0)`, the state at index `j.castSucc` equals the state of `u` started at
`x₀` at index `j.succ`. -/
theorem finiteHorizonRollout_snoc {f : X → U → X} {ℓ : X → U → ℝ} {Vf : X → ℝ}
    {M : ℕ} {Xs : Set X} {Us : Set U} {Xf : Set X} (x₀ : X)
    (u : Fin (M + 1) → U) (w : U) (j : Fin (M + 1)) :
    finiteHorizonRollout ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩
        (f x₀ (u 0)) (Fin.snoc (Fin.tail u) w) j.castSucc =
      finiteHorizonRollout ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ x₀ u j.succ := by
  induction j using Fin.induction with
  | zero =>
      rw [Fin.castSucc_zero, finiteHorizonRollout_zero, finiteHorizonRollout_succ,
          Fin.castSucc_zero, finiteHorizonRollout_zero]
  | succ k ih =>
      rw [Fin.castSucc_succ, finiteHorizonRollout_succ]
      conv_rhs => rw [finiteHorizonRollout_succ]
      rw [Fin.castSucc_succ k]
      rw [ih, Fin.succ_castSucc, Fin.snoc_castSucc]
      rfl

/-- The terminal step of an extended rollout: extending the input sequence `u` of
horizon `M + 1` by a terminal control `w` and restarting the rollout at the
successor `f x₀ (u 0)` reaches `f x w` at the final index, where `x` is the
terminal state of the original rollout.  This combines the one-step recursion with
`finiteHorizonRollout_snoc`. -/
theorem finiteHorizonRollout_snoc_last {f : X → U → X} {ℓ : X → U → ℝ} {Vf : X → ℝ}
    {M : ℕ} {Xs : Set X} {Us : Set U} {Xf : Set X} (x₀ : X) (u : Fin (M + 1) → U) (w : U) :
    finiteHorizonRollout ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ (f x₀ (u 0))
        (Fin.snoc (Fin.tail u) w) (Fin.last (M + 1)) =
      f (finiteHorizonRollout ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ x₀ u (Fin.last (M + 1))) w := by
  rw [← Fin.succ_last M, finiteHorizonRollout_succ]
  rw [finiteHorizonRollout_snoc x₀ u w (Fin.last M), Fin.succ_last, Fin.snoc_last]

/-- Admissibility of an input sequence extended by one terminal control: if `u` is
admissible for the horizon-`M + 1` problem, its terminal state lies in the state
set, and the appended control `w` is admissible with `f`-successor in the terminal
set, then `Fin.snoc (Fin.tail u) w` started at the successor `f x₀ (u 0)` is
admissible for the same horizon-`M + 1` problem.  The first `M` steps reuse the
trajectory of `u` shifted by one index (`finiteHorizonRollout_snoc`) and the last
step is the appended terminal control. -/
theorem finiteHorizonAdmissible_snoc {f : X → U → X} {ℓ : X → U → ℝ} {Vf : X → ℝ}
    {M : ℕ} {Xs : Set X} {Us : Set U} {Xf : Set X} (x₀ : X) (u : Fin (M + 1) → U) (w : U)
    (hadm : FiniteHorizonAdmissible ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ x₀ u)
    (htermXs : finiteHorizonRollout ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ x₀ u
        (Fin.last (M + 1)) ∈ Xs)
    (hwU : w ∈ Us)
    (hwXf : f (finiteHorizonRollout ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ x₀ u
        (Fin.last (M + 1))) w ∈ Xf) :
    FiniteHorizonAdmissible ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ (f x₀ (u 0))
      (Fin.snoc (Fin.tail u) w) := by
  unfold FiniteHorizonAdmissible
  constructor
  · intro k
    constructor
    · rw [finiteHorizonRollout_snoc x₀ u w k]
      by_cases hlast : k.succ = Fin.last (M + 1)
      · rw [hlast]
        exact htermXs
      · obtain ⟨j, hj⟩ := (Fin.exists_castSucc_eq (n := M + 1)).mpr hlast
        rw [← hj]
        exact (hadm.1 j).1
    · by_cases hklast : k = Fin.last M
      · rw [hklast, Fin.snoc_last]
        exact hwU
      · obtain ⟨j, hj⟩ := (Fin.exists_castSucc_eq (n := M)).mpr hklast
        rw [← hj, Fin.snoc_castSucc]
        exact (hadm.1 j.succ).2
  · rw [← Fin.succ_last M, finiteHorizonRollout_succ]
    rw [finiteHorizonRollout_snoc x₀ u w (Fin.last M), Fin.succ_last, Fin.snoc_last]
    exact hwXf

/-- Expanding the total cost of an extended input sequence `Fin.snoc (Fin.tail u) w`: the running
sum shifts by one index along the original rollout, the last stage cost evaluates at the terminal
state `x_N` with input `w`, and the terminal cost evaluates at `f x_N w`. -/
theorem totalCost_snoc (f : X → U → X) (ℓ : X → U → ℝ) (Vf : X → ℝ)
    (M : ℕ) (Xs : Set X) (Us : Set U) (Xf : Set X)
    (x : X) (u : Fin (M + 1) → U) (w : U) :
    finiteHorizonTotalCost ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ (f x (u 0)) (Fin.snoc (Fin.tail u) w) =
      (∑ j : Fin M, ℓ (finiteHorizonRollout ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ x u j.succ.castSucc)
        (u j.succ)) +
        ℓ (finiteHorizonRollout ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ x u (Fin.last (M + 1))) w +
        Vf (f (finiteHorizonRollout ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ x u (Fin.last (M + 1))) w) := by
  unfold finiteHorizonTotalCost
  rw [Fin.sum_univ_castSucc]
  rw [finiteHorizonRollout_snoc_last]
  congr 1
  congr 1
  · refine Finset.sum_congr rfl ?_
    intro j _
    rw [finiteHorizonRollout_snoc, Fin.snoc_castSucc, Fin.tail]
    rw [Fin.castSucc_succ]
  · rw [finiteHorizonRollout_snoc, Fin.snoc_last, Fin.succ_last]

/-- Splitting off the first stage cost from the finite-horizon total cost of sequence `u`, as the
horizon-`M + 1` restatement of `finiteHorizonTotalCost_tail` combined with
`finiteHorizonRollout_tail`. -/
theorem totalCost_succ_split (f : X → U → X) (ℓ : X → U → ℝ) (Vf : X → ℝ)
    (M : ℕ) (Xs : Set X) (Us : Set U) (Xf : Set X)
    (x : X) (u : Fin (M + 1) → U) :
    finiteHorizonTotalCost ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ x u =
      ℓ x (u 0) +
        (∑ j : Fin M, ℓ (finiteHorizonRollout ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ x u j.succ.castSucc)
          (u j.succ)) +
        Vf (finiteHorizonRollout ⟨f, ℓ, Vf, M + 1, Xs, Us, Xf⟩ x u (Fin.last (M + 1))) := by
  unfold finiteHorizonTotalCost
  rw [Fin.sum_univ_succ]
  rw [Fin.castSucc_zero, finiteHorizonRollout_zero]
