/-
Copyright (c) 2026 Igor Zubrycki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Igor Zubrycki
-/
module

public import Mathlib.Algebra.BigOperators.Fin
public import Mathlib.Basic.Real.Basic
public import Mathlib.Data.Set.Basic

/-! # Finite-horizon optimal control

This file sets up the purely set-theoretic data of a finite-horizon deterministic
optimal control problem and its trajectory/cost bookkeeping.  Nothing here uses
topological or vector-space structure: the state and input spaces are arbitrary
types, the dynamics is a bare transition map `f : X → U → X`, the stage and
terminal costs are functions into `ℝ`, and the state/input/terminal constraints
are plain sets.  This is the generic substrate on which the dynamic-programming
value function and the model predictive control layer are later built.

The definitions follow Rawlings, Mayne and Diehl, *Model Predictive Control:
Theory, Computation, and Design*, 2nd ed., 2019, Chapter 1, §1.3
(printed pp. 11–25) for the finite-horizon trajectory and cost, and Chapter 2,
§2.2 (printed p. 91) for the constraint sets `X`, `U` and the terminal set.

## Main definitions

* `FiniteHorizonProblem`: dynamics, stage cost, terminal cost, horizon and the
  state/input/terminal constraint sets.
* `finiteHorizonRollout`: the closed-loop trajectory `x(k)` generated by an input
  sequence `u : Fin N → U`.
* `finiteHorizonTotalCost`: `∑_{k<N} ℓ(x(k), u(k)) + Vf(x(N))`.
* `FiniteHorizonAdmissible`: the state/input/terminal constraint predicate.
* `FiniteHorizonFeasible`: existence of an admissible input sequence.

## Main results

* `finiteHorizonRollout_zero`: the trajectory starts at `x₀`.
* `finiteHorizonRollout_succ`: the one-step recursion defining the trajectory.
* `finiteHorizonTotalCost_zero`: with horizon `0` the total cost is `Vf x₀`.
-/

@[expose] public section

variable {X U : Type*}

/-- A finite-horizon deterministic optimal control problem.

The transition map is `f`, the stage cost is `stageCost`, the terminal cost is
`terminalCost`, the horizon is `horizon` (the number of control steps, so the
trajectory has `horizon + 1` states), and the constraints are the sets
`stateSet`, `inputSet` and `terminalSet` (Rawlings–Mayne–Diehl 2019, Ch. 1
§1.3 and Ch. 2 §2.2). -/
structure FiniteHorizonProblem (X U : Type*) where
  /-- The transition map `x⁺ = f x u`. -/
  (f : X → U → X)
  /-- The stage cost `ℓ x u`. -/
  (stageCost : X → U → ℝ)
  /-- The terminal cost `Vf x`. -/
  (terminalCost : X → ℝ)
  /-- The number of control steps (the trajectory has `horizon + 1` states). -/
  (horizon : ℕ)
  /-- The admissible state set `X`. -/
  (stateSet : Set X)
  /-- The admissible input set `U`. -/
  (inputSet : Set U)
  /-- The terminal constraint set `Xf`. -/
  (terminalSet : Set X)

/-- The closed-loop trajectory of `prob` from `x₀` under the input sequence `u`.

Index `0` is the initial state `x₀` and index `k + 1` is obtained by applying the
dynamics to the state at index `k` with the input `u k`.  This is
`Fin.induction` over the state index domain `Fin (horizon + 1)`. -/
def finiteHorizonRollout (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) : Fin (prob.horizon + 1) → X :=
  Fin.induction x₀ fun k xk => prob.f xk (u k)

/-- The finite-horizon total cost of the input sequence `u` from `x₀`:
the sum of the stage costs along the trajectory plus the terminal cost at the
final state (Rawlings–Mayne–Diehl 2019, Ch. 1 §1.3, printed p. 11). -/
def finiteHorizonTotalCost (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) : ℝ :=
  (∑ k : Fin prob.horizon,
      prob.stageCost (finiteHorizonRollout prob x₀ u k.castSucc) (u k)) +
    prob.terminalCost (finiteHorizonRollout prob x₀ u (Fin.last prob.horizon))

/-- Admissibility of an input sequence: every state `x(k)` for `k < horizon`
lies in `stateSet`, every input `u(k)` lies in `inputSet`, and the terminal state
`x(horizon)` lies in `terminalSet` (Rawlings–Mayne–Diehl 2019, Ch. 2 §2.2,
printed p. 91). -/
def FiniteHorizonAdmissible (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) : Prop :=
  (∀ k : Fin prob.horizon,
      finiteHorizonRollout prob x₀ u k.castSucc ∈ prob.stateSet ∧
        u k ∈ prob.inputSet) ∧
    finiteHorizonRollout prob x₀ u (Fin.last prob.horizon) ∈ prob.terminalSet

/-- Feasibility of a finite-horizon problem from `x₀`: there exists an admissible
input sequence. -/
def FiniteHorizonFeasible (prob : FiniteHorizonProblem X U) (x₀ : X) : Prop :=
  ∃ u, FiniteHorizonAdmissible prob x₀ u

/-- The trajectory at index `0` is the initial state. -/
@[simp]
theorem finiteHorizonRollout_zero (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) : finiteHorizonRollout prob x₀ u 0 = x₀ := by
  unfold finiteHorizonRollout
  rfl

/-- The one-step recursion defining the trajectory: the state at index `k + 1` is
the image under `f` of the state at index `k` with input `u k`. -/
@[simp]
theorem finiteHorizonRollout_succ (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) (k : Fin prob.horizon) :
    finiteHorizonRollout prob x₀ u (Fin.succ k) =
      prob.f (finiteHorizonRollout prob x₀ u k.castSucc) (u k) := by
  unfold finiteHorizonRollout
  exact Fin.induction_succ (motive := fun _ => X) x₀ (fun k xk => prob.f xk (u k)) k

/-- With horizon `0` there are no stage costs and the trajectory consists only of
the initial state, so the total cost is the terminal cost `Vf x₀`. -/
@[simp]
theorem finiteHorizonTotalCost_zero (prob : FiniteHorizonProblem X U) (x₀ : X)
    (u : Fin prob.horizon → U) (h : prob.horizon = 0) :
    finiteHorizonTotalCost prob x₀ u = prob.terminalCost x₀ := by
  obtain ⟨f, ℓ, Vf, N, Xs, Us, Xf⟩ := prob
  subst h
  simp [finiteHorizonTotalCost, finiteHorizonRollout]
