import DynamicalSystems.Mathlib.MeasureTheory.MeasurableSigmaCompactLift
import DynamicalSystems.OptimalControl.ContinuousTime.CesariExistenceArgument
import DynamicalSystems.OptimalControl.ContinuousTime.MinimumTimeTransversality
import DynamicalSystems.OptimalControl.ContinuousTime.StateConstraintComplementarity

#print axioms DynamicalSystems.MeasurableLift.exists_measurable_lift_of_continuous_sigmaCompact
#print axioms OptimalControl.sum_mem_convexHull_tail
#print axioms OptimalControl.exists_weights_of_mem_convexHull_tail
#print axioms OptimalControl.exists_tendsto_tail_convex_combinations_of_weak_tendsto
#print axioms OptimalControl.tendsto_tail_convex_combinations
#print axioms OptimalControl.exists_ae_tendsto_tail_convex_combinations_of_weak_Lp_tendsto
#print axioms OptimalControl.exists_weights_ae_tendsto_of_weak_Lp_tendsto
#print axioms OptimalControl.mem_of_weakCesariProperty_of_tail_combinations
#print axioms OptimalControl.velocityCost_liminf_mem_of_weakCesariProperty
#print axioms OptimalControl.ae_velocityCost_liminf_mem_and_lintegral_le
#print axioms OptimalControl.exists_integrable_cost_epigraph_of_cesari_combinations
#print axioms OptimalControl.exists_integrable_cost_epigraph_of_weak_Lp_tendsto
#print axioms OptimalControl.mem_extremePoints_of_unique_linear_minimum
#print axioms OptimalControl.ae_mem_extremePoints_of_linearControlNormality
#print axioms OptimalControl.ae_mem_extremePoints_of_cyclic_box_minimizing
#print axioms OptimalControl.BoundedState.multiplierMeasure_Ioi_eq_zero_of_terminal_collar
#print axioms OptimalControl.BoundedState.ae_constraint_eq_zero_of_const_on_slack
#print axioms OptimalControl.BoundedState.integral_constraint_eq_zero_of_const_on_slack
#print axioms
  OptimalControl.BoundedState.integral_stateConstraint_eq_zero_of_multiplier_const_on_slack
#print axioms OptimalControl.BoundedState.integrableOn_stateConstraint_of_regularity
#print axioms OptimalControl.BoundedState.intervalIntegrable_stateGradient_velocity_of_regularity
#print axioms
  OptimalControl.BoundedState.intervalIntegrable_multiplier_stateGradient_velocity_of_regularity
