import DynamicalSystems.Mathlib.MeasureTheory.MovingIntervalCompactness
import DynamicalSystems.OptimalControl.ContinuousTime.CesariExistenceArgument
import DynamicalSystems.OptimalControl.ContinuousTime.CesariMovingInterval

open DynamicalSystems.EquiIntegrableTrajectories
open OptimalControl

#print axioms eventually_mem_Ioo_of_endpoint_tendsto
#print axioms const_on_outer_intervals_of_uniform_tendsto_endpoints
#print axioms integral_difference_law_on_subinterval
#print axioms exists_uniform_limit_endpoints_weak_L1_integral_law
#print axioms mem_of_weakCesariProperty_of_eventually_mem_of_tail_convexHull
#print axioms velocityCost_liminf_mem_of_weakCesariProperty_of_eventually_mem
#print axioms ae_velocityCost_liminf_mem_and_lintegral_le_of_eventually_mem
#print axioms exists_integrable_cost_epigraph_of_cesari_combinations_of_eventually_mem
#print axioms exists_integrable_cost_epigraph_of_weak_Lp_tendsto_of_eventually_mem
#print axioms hasWeakCesariProperty_congr_at_time
#print axioms hasWeakCesariProperty_const_of_isClosed_of_convex
#print axioms mem_state_projection_of_constant_extension
#print axioms exists_limit_endpoints_cost_epigraph_of_unifIntegrable
#print axioms exists_runningCost_tendsto_subseq_of_tendsto_totalCost
#print axioms terminalCost_add_le_of_tendsto_totalCost
#print axioms exists_limit_endpoints_objective_epigraph_of_unifIntegrable
