import DynamicalSystems.OptimalControl.ContinuousTime.IntegratorStateMinimumPrinciple

#print axioms OptimalControl.ConvexStateControlProblem.convex_dynamicsAdmissible
#print axioms OptimalControl.ConvexStateControlProblem.exists_measure_of_isMinimum
#print axioms OptimalControl.ConvexStateControlProblem.exists_normal_measure_of_isMinimum
#print axioms OptimalControl.ConvexStateControlProblem.exists_integrator_candidate
#print axioms OptimalControl.ConvexStateControlProblem.exists_integrator_state_pmp
#print axioms OptimalControl.ConvexStateControlProblem.integratorCostate_increment
#print axioms OptimalControl.ConvexStateControlProblem.integratorCostate_terminal
