/-
Copyright (c) 2026 Igor Zubrycki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Igor Zubrycki
-/
module

public import DynamicalSystems.Control.Geometric.LieBrackets
public import DynamicalSystems.Control.Geometric.LocalControllability
public import DynamicalSystems.Linear.Kalman
public import Mathlib.Analysis.Normed.Module.FiniteDimension
public import Mathlib.LinearAlgebra.FiniteDimensional.Basic

/-! # Accessibility and the Lie Algebra Rank Condition (LARC)

This file formalises the Lie Algebra Rank Condition (LARC) and proves the
first-order bridge theorem connecting linear Kalman controllability to LARC,
following Sontag, *Mathematical Control Theory: Deterministic Finite Dimensional
Systems*, 2nd ed., Springer, 1998, Ch. 4 §4.3 (printed pp. 154–164, especially
Remark 4.3.5 and Lemma 4.3.3).

## Scope fence: Frobenius deferral

Mathlib currently lacks Frobenius' theorem on the integrability of involutive
distributions (existence of integral submanifolds and local foliations; see
Sontag §4.4, pp. 164–176).  Consequently, the geometric necessity direction
(that LARC is necessary for reachable sets to have non-empty interior, Sontag
§4.5, pp. 177–179) and the differential-geometric orbit theorem (Ch. 4
Theorem 9) are deferred.

What is formalised here is the **algebraic and first-order linear bridge**:
for any control system `ẋ = f(x, u)` (in particular control-affine systems
`ẋ = f(x) + ∑ gᵢ(x) uᵢ`), Kalman controllability of the linearization
`(A, B) = (∂ₓf(0,0), ∂ᵤf(0,0))` implies that the Lie algebra generated by the
first-order vector fields has full rank at the origin:
`linearizationControllable f ⇒ lieAlgebraRankCondition (firstOrderVectorFields f) 0`.

This is Sontag's §3.7 → §4 bridge: the Kalman controllability condition is the
first-order shadow of the Lie Algebra Rank Condition.

## Main definitions

* `lieAlgebraRankCondition`: the predicate `dim Δ(x) = dim X`, equivalently
  `Δ(x) = ⊤`, for a family of vector fields `𝓕` at a point `x` (Sontag,
  Definition 4.3.2).
* `linearVectorFields`: the family of affine vector fields consisting of the
  linear drift `x ↦ A x` and the constant input fields `x ↦ B u` for all `u : U`
  (Sontag, Remark 4.3.5).
* `firstOrderVectorFields`: the first-order vector fields of a control system
  `f : X → U → X` at the origin, formed from `linearizationA f` and
  `linearizationB f`.
* `controlAffineSystem`: the control-affine vector field map
  `ẋ = f(x) + ∑ i, uᵢ • gᵢ(x)`.

## Main results

* `lieAlgebraRankCondition_iff_finrank`: in finite dimensions, LARC is
  equivalent to `finrank ℝ (accessibilityDistribution 𝓕 x) = finrank ℝ X`.
* `pow_comp_apply_mem_accessibilityDistribution`: each Kalman vector
  `(A^k) (B u)` belongs to the accessibility distribution at the origin.
* `range_kalmanControllabilityMap_le_accessibilityDistribution`: the range
  of the Kalman controllability map is contained in the accessibility
  distribution at `0`.
* `reachableSubspace_le_accessibilityDistribution`: the reachable subspace
  of `(A, B)` is contained in `accessibilityDistribution (linearVectorFields A B) 0`.
* `larc_of_isControllable`: a controllable linear pair `(A, B)` satisfies LARC
  at the origin.
* `larc_of_firstOrderControllable`: if `linearizationControllable f` holds, then
  the first-order vector fields satisfy LARC at `0`.

## References

* E. D. Sontag, *Mathematical Control Theory: Deterministic Finite Dimensional
  Systems*, 2nd ed., Springer, 1998, Ch. 4 §4.3, printed pp. 154–164.
-/

@[expose] public section

open scoped Topology

variable {X U : Type*}

noncomputable section

/-! ### The Lie Algebra Rank Condition (LARC) -/

section LARC

variable [NormedAddCommGroup X] [NormedSpace ℝ X]

/-- The Lie Algebra Rank Condition (LARC) at `x` for a family of vector fields `𝓕`:
the accessibility distribution `accessibilityDistribution 𝓕 x` has full rank,
i.e. `Δ(x) = ⊤` (Sontag, Definition 4.3.2). -/
def lieAlgebraRankCondition (𝓕 : Set (X → X)) (x : X) : Prop :=
  accessibilityDistribution 𝓕 x = ⊤

/-- In a finite-dimensional state space, LARC is equivalent to the evaluation distribution
having dimension equal to the state dimension `Module.finrank ℝ X` (Sontag, Definition 4.3.2). -/
theorem lieAlgebraRankCondition_iff_finrank [FiniteDimensional ℝ X]
    (𝓕 : Set (X → X)) (x : X) :
    lieAlgebraRankCondition 𝓕 x ↔
      Module.finrank ℝ (accessibilityDistribution 𝓕 x) = Module.finrank ℝ X := by
  constructor
  · intro h
    rw [lieAlgebraRankCondition] at h
    rw [h, finrank_top]
  · intro h
    rw [lieAlgebraRankCondition]
    exact Submodule.eq_top_of_finrank_eq h

end LARC

/-! ### First-order vector fields and the Kalman bridge -/

section KalmanBridge

variable [NormedAddCommGroup X] [NormedSpace ℝ X]
variable [NormedAddCommGroup U] [NormedSpace ℝ U]

/-- The family of affine vector fields of a linear pair `(A, B)`: the linear drift
`x ↦ A x` and the constant input fields `x ↦ B u` for each `u : U`
(Sontag, Remark 4.3.5). -/
def linearVectorFields (A : X →L[ℝ] X) (B : U →L[ℝ] X) : Set (X → X) :=
  insert (fun x ↦ A x) (Set.range fun u ↦ (fun _ ↦ B u))

/-- The first-order (linearized) vector fields of a control system `f : X → U → X`
at the origin (Sontag, Ch. 3 §3.7 and Ch. 4 §4.3). -/
def firstOrderVectorFields (f : X → U → X) : Set (X → X) :=
  linearVectorFields (linearizationA f) (linearizationB f)

/-- The iterated Lie bracket of the linear drift and an input vector field evaluates
at the origin to a signed multiple of the Kalman vector `(A^k) (B u)`. -/
theorem adIter_apply_origin (A : X →L[ℝ] X) (B : U →L[ℝ] X) (k : ℕ) (u : U) :
    adIter (fun y : X ↦ A y) k (fun _ : X ↦ B u) 0 =
      (-1 : ℝ) ^ k • ((A.toLinearMap ^ k) (B u)) :=
  adIter_linear_const A (B u) k 0

/-- Each Kalman vector `(A^k) (B u)` belongs to the accessibility distribution
of the linear vector fields at the origin (Sontag, Remark 4.3.5). -/
theorem pow_comp_apply_mem_accessibilityDistribution
    (A : X →L[ℝ] X) (B : U →L[ℝ] X) (k : ℕ) (u : U) :
    (A.toLinearMap ^ k) (B u) ∈ accessibilityDistribution (linearVectorFields A B) 0 := by
  have hA : (fun y : X ↦ A y) ∈ linearVectorFields A B := Set.mem_insert _ _
  have hB : (fun _ : X ↦ B u) ∈ linearVectorFields A B :=
    Set.mem_insert_of_mem _ ⟨u, rfl⟩
  have h_ad := adIter_apply_mem_accessibilityDistribution hA hB k 0
  rw [adIter_apply_origin] at h_ad
  have h_neg : (-1 : ℝ) ^ k • (-1 : ℝ) ^ k • ((A.toLinearMap ^ k) (B u)) ∈
      accessibilityDistribution (linearVectorFields A B) 0 :=
    Submodule.smul_mem _ _ h_ad
  have h_one : (-1 : ℝ) ^ k * (-1 : ℝ) ^ k = 1 := by
    rw [← mul_pow]
    norm_num
  rw [← mul_smul, h_one, one_smul] at h_neg
  exact h_neg

/-- For each power `k`, the range of `(A^k).comp B` is contained in the
accessibility distribution at the origin. -/
theorem range_pow_comp_le_accessibilityDistribution
    (A : X →L[ℝ] X) (B : U →L[ℝ] X) (k : ℕ) :
    LinearMap.range ((A.toLinearMap ^ k).comp B.toLinearMap) ≤
      accessibilityDistribution (linearVectorFields A B) 0 := by
  rintro y ⟨u, rfl⟩
  simp only [LinearMap.comp_apply]
  exact pow_comp_apply_mem_accessibilityDistribution A B k u

/-- The range of the Kalman controllability map is contained in the accessibility
distribution at `0` (Sontag, Remark 4.3.5). -/
theorem range_kalmanControllabilityMap_le_accessibilityDistribution
    (A : X →L[ℝ] X) (B : U →L[ℝ] X) (n : ℕ) :
    LinearMap.range (LinearMap.kalmanControllabilityMap A.toLinearMap B.toLinearMap n) ≤
      accessibilityDistribution (linearVectorFields A B) 0 := by
  rw [LinearMap.range_kalmanControllabilityMap]
  exact iSup_le fun k ↦ range_pow_comp_le_accessibilityDistribution A B (k : ℕ)

/-- The reachable subspace of `(A, B)` is contained in the accessibility distribution
at the origin (Sontag, Remark 4.3.5). -/
theorem reachableSubspace_le_accessibilityDistribution
    (A : X →L[ℝ] X) (B : U →L[ℝ] X) :
    LinearMap.reachableSubspace A.toLinearMap B.toLinearMap ≤
      accessibilityDistribution (linearVectorFields A B) 0 := by
  rw [LinearMap.reachableSubspace]
  exact iSup_le fun k ↦ range_pow_comp_le_accessibilityDistribution A B k

/-- Controllability of the linear pair `(A, B)` implies the Lie Algebra Rank Condition
at the origin for the linear vector fields (Sontag, Remark 4.3.5). -/
theorem larc_of_isControllable (A : X →L[ℝ] X) (B : U →L[ℝ] X)
    (hcont : LinearMap.IsControllable A.toLinearMap B.toLinearMap) :
    lieAlgebraRankCondition (linearVectorFields A B) 0 := by
  rw [lieAlgebraRankCondition]
  have hreach : LinearMap.reachableSubspace A.toLinearMap B.toLinearMap = ⊤ :=
    (LinearMap.isControllable_iff _ _).mp hcont
  have hle := reachableSubspace_le_accessibilityDistribution A B
  rw [hreach] at hle
  exact le_top.antisymm hle

/-- The first-order accessibility bridge theorem: if the linearization of a control
system `f : X → U → X` at the origin is controllable (`linearizationControllable f`),
then the first-order (linearized) vector fields satisfy the Lie Algebra Rank Condition
at the origin (Sontag, Ch. 3 §3.7 and Ch. 4 §4.3, Remark 4.3.5).

The Lie brackets of the linear drift `x ↦ A x` and constant fields `x ↦ B u`
evaluate at `0` to the columns of the Kalman controllability matrix `A^k B u`.
Thus the Kalman reachability subspace is contained in the accessibility distribution
at `0`, and Kalman controllability implies LARC. -/
theorem larc_of_firstOrderControllable (f : X → U → X)
    (hcont : linearizationControllable f) :
    lieAlgebraRankCondition (firstOrderVectorFields f) 0 :=
  larc_of_isControllable (linearizationA f) (linearizationB f) hcont

end KalmanBridge

/-! ### Control-affine systems -/

section ControlAffine

variable [NormedAddCommGroup X] [NormedSpace ℝ X]

/-- A control-affine system `ẋ = f(x) + ∑ i, uᵢ • gᵢ(x)` with drift `f : X → X`
and control vector fields `g : ι → (X → X)` (Sontag, equation (4.18), p. 154). -/
def controlAffineSystem (f : X → X) {ι : Type*} [Fintype ι] (g : ι → (X → X)) :
    X → (ι → ℝ) → X :=
  fun x u ↦ f x + ∑ i, u i • g i x

/-- Controllability of the linearization of a control-affine system at the origin. -/
def controlAffineLinearizationControllable (f : X → X) {ι : Type*} [Fintype ι]
    (g : ι → (X → X)) : Prop :=
  linearizationControllable (controlAffineSystem f g)

/-- First-order LARC bridge for control-affine systems: if the linearization of the
control-affine system is controllable at the origin, then the first-order vector fields
satisfy LARC at `0` (Sontag, Ch. 4 §4.3). -/
theorem larc_of_firstOrderControllable_controlAffine (f : X → X) {ι : Type*} [Fintype ι]
    (g : ι → (X → X))
    (hcont : controlAffineLinearizationControllable f g) :
    lieAlgebraRankCondition (firstOrderVectorFields (controlAffineSystem f g)) 0 :=
  larc_of_firstOrderControllable (controlAffineSystem f g) hcont

end ControlAffine
