/-
Copyright (c) 2026 Igor Zubrycki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Igor Zubrycki
-/
module

public import Mathlib.Analysis.Calculus.VectorField
public import Mathlib.Analysis.Calculus.FDeriv.Basic
public import Mathlib.Analysis.Calculus.FDeriv.Linear
public import Mathlib.Analysis.Calculus.FDeriv.Const
public import Mathlib.Analysis.Calculus.FDeriv.Add
public import Mathlib.LinearAlgebra.Span.Basic
public import Mathlib.LinearAlgebra.FiniteDimensional.Basic
public import Mathlib.Algebra.Module.LinearMap.End

/-! # Lie brackets of vector fields and accessibility distributions

This file develops the control-theoretic wrapper over Mathlib's Lie bracket of
vector fields (`VectorField.lieBracket`) and formalises the accessibility
distribution generated by a family of control vector fields, following Sontag,
*Mathematical Control Theory: Deterministic Finite Dimensional Systems*, 2nd ed.,
Springer, 1998, Ch. 4 §4.1–§4.3 (printed pp. 141–156).

## Scope fence: Frobenius deferral

Mathlib does not currently contain Frobenius' theorem on the integrability of
involutive distributions (foliations, integral submanifolds, and maximal plaques;
see Sontag §4.4, pp. 164–176).  Consequently, the necessity direction of the
accessibility rank condition (Sontag §4.5, pp. 177–179) and the differential-
geometric flow/orbit theorem (Ch. 4 Theorem 9) are deferred.

This file and its companion `DynamicalSystems.Control.Geometric.Accessibility`
are scoped to the **algebraic and linear-evaluation side** of nonlinear
controllability:
1. the Lie bracket `[V, W](x) = DW(x)(V(x)) - DV(x)(W(x))` of vector fields on a
   normed space, re-using Mathlib's `VectorField.lieBracket ℝ`;
2. iterated adjoint brackets `adIter V k W = (ad V)^k W`;
3. the Lie algebra of vector fields `lieAlgebraOf 𝓕` generated by a family `𝓕`;
4. the evaluation distribution (accessibility distribution)
   `accessibilityDistribution 𝓕 x = span { V(x) | V ∈ lieAlgebraOf 𝓕 }`;
5. exact evaluation identities for affine and linear vector fields reproducing the
   powers of the linearization operator `(A^k) b`.

## Main definitions

* `lieBracket`: thin wrapper over `VectorField.lieBracket ℝ` for vector fields on
  a real normed space `X`.
* `ad`: adjoint operator `ad V W = [V, W]`.
* `adIter`: iterated adjoint operator `adIter V k W = (ad V)^k W`.
* `InLieAlgebra`: inductive predicate defining membership in the Lie algebra
  generated by a family of vector fields `𝓕 : Set (X → X)`.
* `lieAlgebraOf`: the Lie algebra generated by `𝓕` as a submodule of `X → X`.
* `accessibilityDistribution`: the evaluation submodule `Δ(x) ≤ X` spanned by
  evaluating all elements of `lieAlgebraOf 𝓕` at `x`.

## Main results

* `lieBracket_swap`, `lieBracket_self`: skew-symmetry and vanishing of self-bracket.
* `contDiff_lieBracket`: smoothness preservation of the Lie bracket.
* `lieAlgebraOf_bracket`: closure of `lieAlgebraOf 𝓕` under Lie bracket.
* `adIter_mem_lieAlgebraOf`: iterated Lie brackets of elements in `lieAlgebraOf 𝓕`
  remain in `lieAlgebraOf 𝓕`.
* `adIter_apply_mem_accessibilityDistribution`: iterated brackets evaluate into
  the accessibility distribution at any point.
* `lieBracket_linear_const`, `lieBracket_const_linear`: Lie brackets of a linear
  field `x ↦ A x` and a constant field `x ↦ b` compute to `∓ A b`.
* `adIter_linear_const`: `(ad (A ·))^k b` evaluates to `(-1)^k • (A^k b)`.

## References

* E. D. Sontag, *Mathematical Control Theory: Deterministic Finite Dimensional
  Systems*, 2nd ed., Springer, 1998, Ch. 4 §4.1–§4.3, printed pp. 141–156.
-/

@[expose] public section

open scoped Topology ContDiff

variable {X : Type*}

noncomputable section

section LieBracketDef

variable [NormedAddCommGroup X] [NormedSpace ℝ X]

/-- The Lie bracket `[V, W]` of two vector fields `V, W : X → X` on a normed space `X`,
defined via Mathlib's `VectorField.lieBracket ℝ V W`:
`[V, W](x) = DW(x)(V(x)) - DV(x)(W(x))` (Sontag, Definition 4.1.1). -/
def lieBracket (V W : X → X) : X → X :=
  VectorField.lieBracket ℝ V W

/-- Unfolding of `lieBracket` into the displayed Fréchet derivative formula. -/
theorem lieBracket_apply (V W : X → X) (x : X) :
    lieBracket V W x = fderiv ℝ W x (V x) - fderiv ℝ V x (W x) :=
  rfl

/-- Adjoint operator `ad V W = [V, W]` on vector fields (Sontag, display (4.4)). -/
def ad (V W : X → X) : X → X :=
  lieBracket V W

@[simp]
theorem ad_apply (V W : X → X) : ad V W = lieBracket V W :=
  rfl

/-- Iterated Lie bracket / adjoint operator:
`adIter V 0 W = W`, `adIter V (k + 1) W = [V, adIter V k W]`.
This satisfies `adIter V k W = (ad V)^k W` (Sontag, Remark 4.3.5). -/
def adIter (V : X → X) : ℕ → (X → X) → (X → X)
  | 0, W => W
  | k + 1, W => lieBracket V (adIter V k W)

@[simp]
theorem adIter_zero (V W : X → X) : adIter V 0 W = W :=
  rfl

@[simp]
theorem adIter_succ (V : X → X) (k : ℕ) (W : X → X) :
    adIter V (k + 1) W = lieBracket V (adIter V k W) :=
  rfl

/-! ### Algebraic and smoothness properties -/

/-- Skew-symmetry of the Lie bracket: `[V, W](x) = - [W, V](x)`. -/
theorem lieBracket_swap (V W : X → X) (x : X) :
    lieBracket V W x = - lieBracket W V x :=
  VectorField.lieBracket_swap

/-- Vanishing of the Lie bracket of a vector field with itself: `[V, V] = 0`. -/
@[simp]
theorem lieBracket_self (V : X → X) :
    lieBracket V V = 0 :=
  VectorField.lieBracket_self

/-- Linearity of the Lie bracket in the left argument over vector addition. -/
theorem lieBracket_add_left {V₁ V₂ W : X → X} {x : X}
    (hV₁ : DifferentiableAt ℝ V₁ x) (hV₂ : DifferentiableAt ℝ V₂ x) :
    lieBracket (V₁ + V₂) W x = lieBracket V₁ W x + lieBracket V₂ W x :=
  VectorField.lieBracket_add_left hV₁ hV₂

/-- Linearity of the Lie bracket in the right argument over vector addition. -/
theorem lieBracket_add_right {V W₁ W₂ : X → X} {x : X}
    (hW₁ : DifferentiableAt ℝ W₁ x) (hW₂ : DifferentiableAt ℝ W₂ x) :
    lieBracket V (W₁ + W₂) x = lieBracket V W₁ x + lieBracket V W₂ x :=
  VectorField.lieBracket_add_right hW₁ hW₂

/-- Linearity of the Lie bracket in the left argument over scalar multiplication. -/
theorem lieBracket_smul_left {c : ℝ} {V W : X → X} {x : X}
    (hV : DifferentiableAt ℝ V x) :
    lieBracket (c • V) W x = c • lieBracket V W x :=
  VectorField.lieBracket_const_smul_left hV

/-- Linearity of the Lie bracket in the right argument over scalar multiplication. -/
theorem lieBracket_smul_right {c : ℝ} {V W : X → X} {x : X}
    (hW : DifferentiableAt ℝ W x) :
    lieBracket V (c • W) x = c • lieBracket V W x :=
  VectorField.lieBracket_const_smul_right hW

/-- Smoothness closure: the Lie bracket of two `C^n` vector fields is `C^m`
whenever `m + 1 ≤ n` (Sontag §4.1). -/
theorem contDiff_lieBracket {m n : ℕ∞ω} {V W : X → X}
    (hV : ContDiff ℝ n V) (hW : ContDiff ℝ n W) (hmn : m + 1 ≤ n) :
    ContDiff ℝ m (lieBracket V W) :=
  ContDiff.lieBracket_vectorField hV hW hmn

/-- Smoothness closure for smooth vector fields: the Lie bracket of smooth
(`C^∞`) vector fields is smooth. -/
theorem contDiff_top_lieBracket {V W : X → X}
    (hV : ContDiff ℝ ⊤ V) (hW : ContDiff ℝ ⊤ W) :
    ContDiff ℝ ⊤ (lieBracket V W) :=
  ContDiff.lieBracket_vectorField hV hW le_rfl

end LieBracketDef

/-! ### The accessibility Lie algebra and distribution -/

section Distribution

variable [NormedAddCommGroup X] [NormedSpace ℝ X]

/-- Inductive predicate specifying the Lie algebra of vector fields generated by a set `𝓕`:
the smallest subspace of `X → X` containing `𝓕` and closed under Lie brackets
(Sontag, Definition 4.1.3 and Lemma 4.1.4). -/
inductive InLieAlgebra (𝓕 : Set (X → X)) : (X → X) → Prop
  | of_mem {V : X → X} (hV : V ∈ 𝓕) : InLieAlgebra 𝓕 V
  | zero : InLieAlgebra 𝓕 0
  | add {V W : X → X} (hV : InLieAlgebra 𝓕 V) (hW : InLieAlgebra 𝓕 W) :
      InLieAlgebra 𝓕 (V + W)
  | smul {V : X → X} (c : ℝ) (hV : InLieAlgebra 𝓕 V) :
      InLieAlgebra 𝓕 (c • V)
  | bracket {V W : X → X} (hV : InLieAlgebra 𝓕 V) (hW : InLieAlgebra 𝓕 W) :
      InLieAlgebra 𝓕 (lieBracket V W)

/-- The Lie algebra of vector fields generated by a family `𝓕 : Set (X → X)` as a submodule
of `X → X` (Sontag, Definition 4.1.3 and Lemma 4.1.4). -/
def lieAlgebraOf (𝓕 : Set (X → X)) : Submodule ℝ (X → X) where
  carrier := { V | InLieAlgebra 𝓕 V }
  zero_mem' := InLieAlgebra.zero
  add_mem' hV hW := InLieAlgebra.add hV hW
  smul_mem' c _ hV := InLieAlgebra.smul c hV

/-- Membership in the generated Lie algebra from membership in the generating set. -/
theorem mem_lieAlgebraOf {𝓕 : Set (X → X)} {V : X → X} (hV : V ∈ 𝓕) :
    V ∈ lieAlgebraOf 𝓕 :=
  InLieAlgebra.of_mem hV

/-- Closure of the generated Lie algebra under Lie bracket. -/
theorem lieAlgebraOf_bracket {𝓕 : Set (X → X)} {V W : X → X}
    (hV : V ∈ lieAlgebraOf 𝓕) (hW : W ∈ lieAlgebraOf 𝓕) :
    lieBracket V W ∈ lieAlgebraOf 𝓕 :=
  InLieAlgebra.bracket hV hW

/-- Iterated Lie brackets of elements in the Lie algebra remain in the Lie algebra. -/
theorem adIter_mem_lieAlgebraOf {𝓕 : Set (X → X)} {V W : X → X}
    (hV : V ∈ lieAlgebraOf 𝓕) (hW : W ∈ lieAlgebraOf 𝓕) (k : ℕ) :
    adIter V k W ∈ lieAlgebraOf 𝓕 := by
  induction k with
  | zero => exact hW
  | succ k ih => exact lieAlgebraOf_bracket hV ih

/-- The evaluation distribution `Δ(x)` of a family of vector fields `𝓕`:
the linear subspace of `X` spanned by evaluating all elements of the Lie algebra
`lieAlgebraOf 𝓕` at `x`, i.e., `Δ(x) = span { V(x) | V ∈ lieAlgebraOf 𝓕 }`
(Sontag, Definition 4.3.2). -/
def accessibilityDistribution (𝓕 : Set (X → X)) (x : X) : Submodule ℝ X :=
  Submodule.span ℝ { V x | V ∈ lieAlgebraOf 𝓕 }

/-- Every vector field in `lieAlgebraOf 𝓕` evaluates at `x` into `accessibilityDistribution 𝓕 x`. -/
theorem mem_accessibilityDistribution_of_mem_lieAlgebra {𝓕 : Set (X → X)} {V : X → X}
    (hV : V ∈ lieAlgebraOf 𝓕) (x : X) :
    V x ∈ accessibilityDistribution 𝓕 x :=
  Submodule.subset_span ⟨V, hV, rfl⟩

/-- Every generating vector field in `𝓕` evaluates at `x` into `accessibilityDistribution 𝓕 x`. -/
theorem mem_accessibilityDistribution_of_mem {𝓕 : Set (X → X)} {V : X → X}
    (hV : V ∈ 𝓕) (x : X) :
    V x ∈ accessibilityDistribution 𝓕 x :=
  mem_accessibilityDistribution_of_mem_lieAlgebra (mem_lieAlgebraOf hV) x

/-- Iterated Lie brackets of generating fields evaluate at `x` into the
accessibility distribution `accessibilityDistribution 𝓕 x`. -/
theorem adIter_apply_mem_accessibilityDistribution {𝓕 : Set (X → X)} {V W : X → X}
    (hV : V ∈ 𝓕) (hW : W ∈ 𝓕) (k : ℕ) (x : X) :
    adIter V k W x ∈ accessibilityDistribution 𝓕 x :=
  mem_accessibilityDistribution_of_mem_lieAlgebra
    (adIter_mem_lieAlgebraOf (mem_lieAlgebraOf hV) (mem_lieAlgebraOf hW) k) x

/-- Monotonicity of the accessibility distribution with respect to the generating family. -/
theorem accessibilityDistribution_mono {𝓕₁ 𝓕₂ : Set (X → X)} (h : 𝓕₁ ⊆ 𝓕₂) (x : X) :
    accessibilityDistribution 𝓕₁ x ≤ accessibilityDistribution 𝓕₂ x := by
  apply Submodule.span_mono
  rintro _ ⟨V, hV, rfl⟩
  refine ⟨V, ?_, rfl⟩
  induction hV with
  | of_mem hm => exact InLieAlgebra.of_mem (h hm)
  | zero => exact InLieAlgebra.zero
  | add _ _ ih1 ih2 => exact InLieAlgebra.add ih1 ih2
  | smul c _ ih => exact InLieAlgebra.smul c ih
  | bracket _ _ ih1 ih2 => exact InLieAlgebra.bracket ih1 ih2

end Distribution

/-! ### Lie brackets of linear and constant vector fields -/

section LinearBrackets

variable [NormedAddCommGroup X] [NormedSpace ℝ X]

/-- The Lie bracket of two constant vector fields is zero (Sontag, Remark 4.3.5). -/
@[simp]
theorem lieBracket_const_const (b₁ b₂ : X) :
    lieBracket (fun _ : X ↦ b₁) (fun _ : X ↦ b₂) = 0 := by
  ext x
  simp only [lieBracket_apply, Pi.zero_apply]
  rw [fderiv_const_apply, fderiv_const_apply]
  simp

/-- The Lie bracket of a linear vector field `x ↦ A x` and a constant vector field `x ↦ b`
is the constant vector field `- A b` (Sontag, Remark 4.3.5). -/
theorem lieBracket_linear_const (A : X →L[ℝ] X) (b : X) (x : X) :
    lieBracket (fun y : X ↦ A y) (fun _ : X ↦ b) x = - A b := by
  simp only [lieBracket_apply]
  rw [fderiv_const_apply, ContinuousLinearMap.fderiv]
  simp

/-- The Lie bracket of a constant vector field `x ↦ b` and a linear vector field `x ↦ A x`
is the constant vector field `A b` (Sontag, Remark 4.3.5). -/
theorem lieBracket_const_linear (A : X →L[ℝ] X) (b : X) (x : X) :
    lieBracket (fun _ : X ↦ b) (fun y : X ↦ A y) x = A b := by
  rw [lieBracket_swap, lieBracket_linear_const, neg_neg]

/-- Iterated Lie bracket of a linear vector field `x ↦ A x` and a constant field `x ↦ b`:
`adIter (A ·) k (const b)` is the constant vector field `(-1)^k • ((A^k) b)`
(Sontag, Remark 4.3.5). -/
theorem adIter_linear_const (A : X →L[ℝ] X) (b : X) (k : ℕ) (x : X) :
    adIter (fun y : X ↦ A y) k (fun _ : X ↦ b) x =
      (-1 : ℝ) ^ k • ((A.toLinearMap ^ k) b) := by
  induction k generalizing x with
  | zero =>
    simp only [adIter_zero, pow_zero, one_smul]
    rfl
  | succ k ih =>
    rw [adIter_succ]
    have heq : adIter (fun y ↦ A y) k (fun _ ↦ b) =
        fun _ : X ↦ (-1 : ℝ) ^ k • ((A.toLinearMap ^ k) b) := by
      ext y; exact ih y
    rw [heq, lieBracket_linear_const]
    rw [pow_succ, mul_smul, neg_one_smul]
    rw [map_smul, smul_neg]
    congr 1
    rw [pow_succ']
    rfl

end LinearBrackets
