import DynamicalSystems.Basic.NonAutonomous
import DynamicalSystems.Mathlib.Analysis.ODE.GlobalExistenceLinear
import DynamicalSystems.Mathlib.Analysis.ODE.NeedleDisplacement
import DynamicalSystems.Mathlib.Analysis.ODE.StateTransition
import DynamicalSystems.Mathlib.Analysis.ODE.StateTransitionExistence
import DynamicalSystems.Mathlib.Analysis.ODE.StateTransitionPiecewise
import DynamicalSystems.OptimalControl.ContinuousTime.ActualNeedleCostRemainder
import DynamicalSystems.OptimalControl.ContinuousTime.AdjointExistence
import DynamicalSystems.OptimalControl.ContinuousTime.AugmentedCostate
import DynamicalSystems.OptimalControl.ContinuousTime.BolzaAugmentation
import DynamicalSystems.OptimalControl.ContinuousTime.ConstrainedCoVMultipliers
import DynamicalSystems.OptimalControl.ContinuousTime.CovectorPMPBridge
import DynamicalSystems.OptimalControl.ContinuousTime.DynamicProgrammingMinPrincipleFromHJB
import DynamicalSystems.OptimalControl.ContinuousTime.GeometricMinimumPrinciple
import DynamicalSystems.OptimalControl.ContinuousTime.GeometricNeedlePMP
import DynamicalSystems.OptimalControl.ContinuousTime.HJBResidualBridge
import DynamicalSystems.OptimalControl.ContinuousTime.IntegralAdmissibility
import DynamicalSystems.OptimalControl.ContinuousTime.MinimumFuel
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleCostIdentity
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleCostRemainder
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleFamily
import DynamicalSystems.OptimalControl.ContinuousTime.NeedlePMP
import DynamicalSystems.OptimalControl.ContinuousTime.NeedlePMPOnHorizon
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleSeparation
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleTerminalFamily
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleTrajectory
import DynamicalSystems.OptimalControl.ContinuousTime.OptimalityGeometry
import DynamicalSystems.OptimalControl.ContinuousTime.ReferenceExtension
import DynamicalSystems.Mathlib.Analysis.ODE.TerminalSensitivity
import DynamicalSystems.OptimalControl.ContinuousTime.TimeReparametrization
import DynamicalSystems.OptimalControl.ContinuousTime.TimeReparametrizationFamily
import DynamicalSystems.OptimalControl.ContinuousTime.UniformNeedleRemainder
import DynamicalSystems.OptimalControl.ContinuousTime.UniformTaylorRemainder
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.ClassicalAdmissibility
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.ClassicalAdmissibilityOCP
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.HorizonLocality
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.QuadraticCost
import DynamicalSystemsTest.Mathlib.Analysis.ODE.NonautonomousFlowOrder
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.NotSufficient
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.PointwiseRepresentative

/-! Kernel dependency audit of the optimal-control endpoints.

`#print axioms` of the principal public declarations, the relocated examples,
and the generic ODE/analysis support they rest on. Every audited declaration
must depend only on `propext`, `Classical.choice`, and `Quot.sound`. -/

#print axioms AutonomousFlow.toNonautonomousFlow
#print axioms HJBResidualBridge.hjb_value_gradient_adjoint
#print axioms IsoperimetricVariation.exists_firstVariation_multiplier_of_curve_family
#print axioms IsoperimetricVariation.exists_normal_multiplier
#print axioms IsoperimetricVariation.exists_normal_multiplier_apply
#print axioms IsoperimetricVariation.exists_normal_multiplier_of_curve_family
#print axioms IsoperimetricVariation.exists_normal_multipliers
#print axioms exists_adjointOn_Icc
#print axioms exists_costate_of_spatial_derivatives
#print axioms integral_adjoint_pairing_with_running_term
#print axioms hasDerivWithinAt_adjoint_pairing
#print axioms hasGradientAt_hamiltonian
#print axioms integral_adjoint_pairing
#print axioms pmpConditions_of_covector
#print axioms PMPExamples.HorizonLocality.no_global_nominal_zero_bound
#print axioms PMPExamples.HorizonLocality.regularity
#print axioms UniformSmall.tendsto_scaled_integral
#print axioms UniformVanishing.tendsto_scaled_needle_integral
#print axioms cost_difference_eq_impulse_add_actualNeedleCostRemainder
#print axioms exists_eventually_controlIncrementError_le_linear
#print axioms exists_uniform_increment_bound_near_reference
#print axioms norm_needleCostRemainder_le_quadratic
#print axioms norm_taylorError_le_of_derivative_bound
#print axioms norm_taylorError_le_quadratic
#print axioms tendsto_scaled_actualNeedleCostFamilyRemainder
#print axioms tendsto_scaled_actualNeedleCostFamilyRemainder_of_C1
#print axioms tendsto_scaled_actualNeedleCostFamilyRemainder_of_continuous
#print axioms tendsto_scaled_of_quadratic_bound
#print axioms tendsto_scaled_needleCostRemainder_of_uniformSmall
#print axioms tendsto_scaled_needleCostRemainder_of_uniformVanishing
#print axioms tendsto_scaled_terminal_taylorError
#print axioms uniformSmall_taylorError
#print axioms uniformVanishing_controlIncrementError
#print axioms uniform_taylorError_near_reference
#print axioms GlobalSmoothNeedleData.exists_costate
#print axioms hamiltonianMinimizing_of_positive_time_jumps
#print axioms needleCostate_of_globalIntegralOptimality
#print axioms needleCostate_of_integralOptimality_smooth
#print axioms NeedleIntegralModel.isIntegralAdmissiblePair_clampTime_iff
#print axioms needleCostate_of_integralOptimality_onHorizon
#print axioms PMPExamples.ClassicalAdmissibility.ScalarModel.reference_has_no_normal_pmp
#print axioms PMPExamples.ClassicalAdmissibility.ScalarModel.reference_optimal
#print axioms PMPExamples.ClassicalAdmissibility.ContinuousOCPAdapter.optimality_does_not_imply_pmp
#print axioms PMPExamples.ClassicalAdmissibility.ContinuousOCPAdapter.problem_data_smooth
#print axioms PMPExamples.ClassicalAdmissibility.ContinuousOCPAdapter.reference_isOptimalPair
#print axioms PMPExamples.ClassicalAdmissibility.ContinuousOCPAdapter.reference_no_costate
#print axioms PMPExamples.ClassicalAdmissibility.ContinuousOCPAdapter.reference_smooth
#print axioms PMPExamples.QuadraticCost.explicit_costate
#print axioms PMPExamples.QuadraticCost.pmp_from_general_theorem
#print axioms PMPExamples.QuadraticCost.reference_optimal
#print axioms PMPExamples.QuadraticCost.running_not_globally_lipschitz
#print axioms IsStateTransition.duhamel_cancellation
#print axioms IsStateTransition.terminal_covector_derivative
#print axioms IsStateTransition.variationOfConstants
#print axioms IsStateTransition.variationOfConstants_off_countable
#print axioms PMPExamples.PointwiseRepresentative.optimal_without_pointwise_pmp
#print axioms costAugmentedEndpoint_eq_terminal_of_admissible
#print axioms exists_augmented_stateTransitionOn_Icc
#print axioms exists_geometricNormalPMP_of_primitive_data
#print axioms exists_needle_endpointTangent_of_primitive_data
#print axioms exists_normal_augmented_terminal_covector
#print axioms hahnBanach_needle_inequality
#print axioms integralAdmissible_bolzaCostLift
#print axioms integralAdmissible_of_augmented
#print axioms integralOptimal_bolzaCostLift
#print axioms integralOptimal_costSlope_nonneg
#print axioms integralOptimal_hahnBanach_needle_inequality
#print axioms integralOptimal_implies_PMP_via_hahnBanach
#print axioms integralOptimal_implies_PMP_via_hahnBanach_of_integral_reference
#print axioms integralOptimal_normal_covector_of_endpointTangents
#print axioms nonneg_of_eventually_minimizing_costSlope
#print axioms terminalCost_costSlope_of_endpointTangent_punctured
#print axioms TimeReparametrization.actualCornerCost_isLocalMin_of_ambient_min
#print axioms TimeReparametrization.actualCornerCost_isLocalMin_of_optimal_duration
#print axioms TimeReparametrization.concatenate_continuous
#print axioms TimeReparametrization.concatenate_isPiecewiseC1
#print axioms TimeReparametrization.concatenate_mem_fixedEndpointPiecewiseC1Curves
#print axioms TimeReparametrization.continuousOn_rescaledDensityDerivative
#print axioms TimeReparametrization.corner_energy_eq_of_actual_min
#print axioms TimeReparametrization.corner_energy_eq_of_cvFunctional_min
#print axioms TimeReparametrization.corner_energy_eq_of_eulerLagrange_min
#print axioms TimeReparametrization.cvFunctional_concatenate
#print axioms TimeReparametrization.cvFunctional_durationExchange
#print axioms TimeReparametrization.durationExchange_endpoints
#print axioms TimeReparametrization.durationExchange_isPiecewiseC1
#print axioms TimeReparametrization.durationExchange_mem_fixedEndpointPiecewiseC1Curves
#print axioms TimeReparametrization.durationExchange_zero
#print axioms TimeReparametrization.energy_eq_of_eulerLagrange
#print axioms TimeReparametrization.exchanged_durations
#print axioms TimeReparametrization.hasDerivAt_actualArcCost_energy
#print axioms TimeReparametrization.hasDerivAt_actualCornerCost
#print axioms TimeReparametrization.hasDerivAt_concatenate_left
#print axioms TimeReparametrization.hasDerivAt_concatenate_right
#print axioms TimeReparametrization.hasDerivAt_energy_zero
#print axioms TimeReparametrization.hasDerivAt_rescaledArc
#print axioms TimeReparametrization.hasDerivAt_rescaledArcCost
#print axioms TimeReparametrization.hasDerivAt_rescaledArcCost_energy
#print axioms TimeReparametrization.hasDerivAt_rescaledDensity
#print axioms TimeReparametrization.rescaledArcCost_eq_actual
#print axioms TimeReparametrization.rescaledDensityDerivative_one
#print axioms TimeReparametrization.rescaled_arcs_preserve_join
#print axioms TimeReparametrization.rescaling_factors_pos
#print axioms TimeReparametrization.state_fderiv_apply
#print axioms TimeReparametrization.velocity_fderiv_apply
#print axioms duhamel_cancellation_right
#print axioms exists_stateTransitionOn_Icc
#print axioms terminal_sensitivity_of_right_ODE
#print axioms terminal_tangent_of_right_ODE
#print axioms UniformSmall.clm_apply
#print axioms variationOfConstants_right_of_backward
#print axioms MinimumFuel.boxHamiltonian_eq_sum
#print axioms MinimumFuel.boxSelector_minimizes
#print axioms MinimumFuel.box_minimizer_iff_coordinate_minimizers
#print axioms MinimumFuel.box_minimizer_iff_switchingLaw
#print axioms MinimumFuel.box_one_eq_unitBox
#print axioms MinimumFuel.controlAffineHamiltonian_eq
#print axioms MinimumFuel.hamiltonianMinimizing_iff_box_minimum
#print axioms MinimumFuel.hamiltonianMinimizing_iff_switchingLaw
#print axioms MinimumFuel.scalarSelector_minimizes
#print axioms MinimumFuel.scalar_minimizer_iff_eq_lower
#print axioms MinimumFuel.scalar_minimizer_iff_eq_upper
#print axioms MinimumFuel.scalar_minimizer_iff_eq_zero
#print axioms MinimumFuel.scalar_minimizer_iff_switchingLaw
#print axioms MinimumFuel.scalar_minimizer_neg_threshold_iff
#print axioms MinimumFuel.scalar_minimizer_pos_threshold_iff
#print axioms NeedleIntegralModel.HamiltonianMinimizing_congr_state
#print axioms NeedleIntegralModel.IsIntegralAdmissiblePair.congr_state
#print axioms NeedleIntegralModel.IsIntegralAdmissiblePair.continuousOn
#print axioms NeedleIntegralModel.IsIntegralAdmissiblePair.hasDerivWithinAt
#print axioms NeedleIntegralModel.IsIntegralOptimalPair.congr_state
#print axioms NeedleIntegralModel.costateEquation_congr_state
#print axioms NeedleIntegralModel.exists_feasible_needle
#print axioms NeedleIntegralModel.exists_feasible_needle_family
#print axioms NeedleIntegralModel.exists_frozen_forcing_bound
#print axioms NeedleIntegralModel.exists_global_optimal_reference_extension
#print axioms NeedleIntegralModel.exists_global_optimal_reference_of_integral
#print axioms NeedleIntegralModel.exists_global_reference_extension
#print axioms NeedleIntegralModel.exists_spliced_solution
#print axioms NeedleIntegralModel.intervalIntegrable_needle_branches
#print axioms NeedleIntegralModel.of_classical
#print axioms NeedleIntegralModel.of_right_derivative
#print axioms NeedleIntegralModel.splice_continuous
#print axioms NeedleIntegralModel.splice_hasDerivWithinAt
#print axioms NeedleIntegralModel.terminal_tangent_of_constructed_family
#print axioms NeedleIntegralModel.totalCost_eq_of_eqOn
#print axioms NeedleIntegralModel.transversalityCondition_congr_state
#print axioms NonautonomousFlow.ext
#print axioms NonautonomousFlow.toAutonomousFlow
#print axioms NonautonomousFlowOrder.bundled_reverse
#print axioms NonautonomousFlowOrder.bundled_solves
#print axioms NonautonomousFlowOrder.cocycle
#print axioms NonautonomousFlowOrder.existsUnique_bundled_solution
#print axioms NonautonomousFlowOrder.field_continuous
#print axioms NonautonomousFlowOrder.field_lipschitz
#print axioms NonautonomousFlowOrder.field_zero_bound
#print axioms NonautonomousFlowOrder.reversed_composition_fails
#print axioms NonautonomousFlowOrder.solution_eq_bundled
#print axioms NonautonomousFlowOrder.solves_ode
#print axioms PMPExamples.NotSufficient.competitor_admissible
#print axioms PMPExamples.NotSufficient.competitor_cost
#print axioms PMPExamples.NotSufficient.pmp_does_not_imply_optimality
#print axioms PMPExamples.NotSufficient.problem_data_smooth
#print axioms PMPExamples.NotSufficient.reference_cost
#print axioms PMPExamples.NotSufficient.reference_not_optimal
#print axioms PMPExamples.NotSufficient.reference_satisfies_pmp
#print axioms existsUnique_nonAutonomousFlow
#print axioms exists_nonAutonomousFlow
#print axioms hjbCostateEquation_of_residual
#print axioms hjbPMPAssembly_of_residual
#print axioms needleTrajectoryFirstOrder
#print axioms needle_displacement_bound_after_spike
#print axioms needle_displacement_firstOrder_of_integral_solutions
#print axioms unique_nonAutonomousFlow
