import DynamicalSystems.OptimalControl.ContinuousTime.ConstrainedCoVMultipliers
import DynamicalSystems.OptimalControl.ContinuousTime.DynamicProgrammingMinPrincipleFromHJB
import DynamicalSystems.OptimalControl.ContinuousTime.GeometricMinimumPrinciple
import DynamicalSystems.OptimalControl.ContinuousTime.MinimumFuel
import DynamicalSystems.OptimalControl.ContinuousTime.NeedlePMPOnHorizon
import DynamicalSystems.OptimalControl.ContinuousTime.TimeReparametrizationFamily

/-! The six compiled campaign scopes; general weak K4 remains pending. -/

#check hjbMinimizing_of_residual
#check hjbCostateEquation_of_residual
#check hjbPMPAssembly_of_residual
#check K1NeedlePMP.needleCostate_of_integralOptimality_smooth
#check K1NeedlePMPOnHorizon.needleCostate_of_integralOptimality_onHorizon
#check KirkMedhin.K1.exists_needle_endpointTangent_of_primitive_data
#check KirkMedhin.K1.integralOptimal_normal_covector_of_endpointTangents
#check KirkMedhin.K1.exists_normalized_hahnBanach_terminal_covector
#check KirkMedhin.K1.exists_geometricNormalPMP_of_primitive_data
#check KirkMedhin.K1.integralOptimal_implies_PMP_via_hahnBanach_of_integral_reference
#check IsoperimetricVariation.exists_normal_multiplier
#check IsoperimetricVariation.exists_firstVariation_multiplier_of_curve_family
#check KirkMedhin.TimeReparametrization.hasDerivAt_actualCornerCost
#check KirkMedhin.TimeReparametrization.cvFunctional_durationExchange
#check KirkMedhin.TimeReparametrization.durationExchange_mem_fixedEndpointPiecewiseC1Curves
#check KirkMedhin.TimeReparametrization.corner_energy_eq_of_cvFunctional_min
#check MinimumFuel.scalar_minimizer_iff_switchingLaw
#check MinimumFuel.box_minimizer_iff_switchingLaw
#check MinimumFuel.hamiltonianMinimizing_iff_switchingLaw

#print axioms hjbMinimizing_of_residual
#print axioms hjbCostateEquation_of_residual
#print axioms hjbPMPAssembly_of_residual
#print axioms K1NeedlePMP.needleCostate_of_integralOptimality_smooth
#print axioms K1NeedlePMPOnHorizon.needleCostate_of_integralOptimality_onHorizon
#print axioms KirkMedhin.K1.exists_needle_endpointTangent_of_primitive_data
#print axioms KirkMedhin.K1.integralOptimal_normal_covector_of_endpointTangents
#print axioms KirkMedhin.K1.exists_normalized_hahnBanach_terminal_covector
#print axioms KirkMedhin.K1.exists_geometricNormalPMP_of_primitive_data
#print axioms KirkMedhin.K1.integralOptimal_implies_PMP_via_hahnBanach_of_integral_reference
#print axioms IsoperimetricVariation.exists_normal_multiplier
#print axioms IsoperimetricVariation.exists_firstVariation_multiplier_of_curve_family
#print axioms KirkMedhin.TimeReparametrization.hasDerivAt_actualCornerCost
#print axioms KirkMedhin.TimeReparametrization.cvFunctional_durationExchange
#print axioms KirkMedhin.TimeReparametrization.durationExchange_mem_fixedEndpointPiecewiseC1Curves
#print axioms KirkMedhin.TimeReparametrization.corner_energy_eq_of_cvFunctional_min
#print axioms MinimumFuel.scalar_minimizer_iff_switchingLaw
#print axioms MinimumFuel.box_minimizer_iff_switchingLaw
#print axioms MinimumFuel.hamiltonianMinimizing_iff_switchingLaw
