import Batteries.Tactic.Lint
import DynamicalSystems.Basic.NonAutonomous
import DynamicalSystems.Mathlib.Analysis.ODE.GlobalExistenceLinear
import DynamicalSystems.Mathlib.Analysis.ODE.NeedleDisplacement
import DynamicalSystems.Mathlib.Analysis.ODE.StateTransition
import DynamicalSystems.Mathlib.Analysis.ODE.StateTransitionExistence
import DynamicalSystems.Mathlib.Analysis.ODE.StateTransitionPiecewise
import DynamicalSystems.OptimalControl.ContinuousTime.ActualNeedleCostRemainder
import DynamicalSystems.OptimalControl.ContinuousTime.AdjointExistence
import DynamicalSystems.OptimalControl.ContinuousTime.AdjointPairing
import DynamicalSystems.OptimalControl.ContinuousTime.AugmentedCostate
import DynamicalSystems.OptimalControl.ContinuousTime.BolzaAugmentation
import DynamicalSystems.OptimalControl.ContinuousTime.ConstrainedCoVMultipliers
import DynamicalSystems.OptimalControl.ContinuousTime.CovectorPMPBridge
import DynamicalSystems.OptimalControl.ContinuousTime.DynamicProgrammingMinPrincipleFromHJB
import DynamicalSystems.OptimalControl.ContinuousTime.GeometricMinimumPrinciple
import DynamicalSystems.OptimalControl.ContinuousTime.GeometricNeedlePMP
import DynamicalSystems.OptimalControl.ContinuousTime.HJBResidualBridge
import DynamicalSystems.OptimalControl.ContinuousTime.IntegralAdmissibility
import DynamicalSystems.OptimalControl.ContinuousTime.MinimumFuel
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleCostIdentity
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleCostRemainder
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleFamily
import DynamicalSystems.OptimalControl.ContinuousTime.NeedlePMP
import DynamicalSystems.OptimalControl.ContinuousTime.NeedlePMPOnHorizon
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleSeparation
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleTerminalFamily
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleTrajectory
import DynamicalSystems.OptimalControl.ContinuousTime.OptimalityGeometry
import DynamicalSystems.OptimalControl.ContinuousTime.ReferenceExtension
import DynamicalSystems.OptimalControl.ContinuousTime.TerminalNeedleSensitivity
import DynamicalSystems.OptimalControl.ContinuousTime.TimeReparametrization
import DynamicalSystems.OptimalControl.ContinuousTime.TimeReparametrizationFamily
import DynamicalSystems.OptimalControl.ContinuousTime.UniformNeedleRemainder
import DynamicalSystems.OptimalControl.ContinuousTime.UniformTaylorRemainder
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.ClassicalAdmissibility
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.ClassicalAdmissibilityOCP
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.HorizonLocality
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.QuadraticCost
import DynamicalSystemsTest.KirkMedhin.NonautonomousFlowOrder
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.NotSufficient
import DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.PointwiseRepresentative

/-! Exact-module declaration lint for all delivered implementation and regression modules. -/

#lint in DynamicalSystems.Basic.NonAutonomous
#lint in DynamicalSystems.Mathlib.Analysis.ODE.GlobalExistenceLinear
#lint in DynamicalSystems.Mathlib.Analysis.ODE.NeedleDisplacement
#lint in DynamicalSystems.Mathlib.Analysis.ODE.StateTransition
#lint in DynamicalSystems.Mathlib.Analysis.ODE.StateTransitionExistence
#lint in DynamicalSystems.Mathlib.Analysis.ODE.StateTransitionPiecewise
#lint in DynamicalSystems.OptimalControl.ContinuousTime.ActualNeedleCostRemainder
#lint in DynamicalSystems.OptimalControl.ContinuousTime.AdjointExistence
#lint in DynamicalSystems.OptimalControl.ContinuousTime.AdjointPairing
#lint in DynamicalSystems.OptimalControl.ContinuousTime.AugmentedCostate
#lint in DynamicalSystems.OptimalControl.ContinuousTime.BolzaAugmentation
#lint in DynamicalSystems.OptimalControl.ContinuousTime.ConstrainedCoVMultipliers
#lint in DynamicalSystems.OptimalControl.ContinuousTime.CovectorPMPBridge
#lint in DynamicalSystems.OptimalControl.ContinuousTime.DynamicProgrammingMinPrincipleFromHJB
#lint in DynamicalSystems.OptimalControl.ContinuousTime.GeometricMinimumPrinciple
#lint in DynamicalSystems.OptimalControl.ContinuousTime.GeometricNeedlePMP
#lint in DynamicalSystems.OptimalControl.ContinuousTime.HJBResidualBridge
#lint in DynamicalSystems.OptimalControl.ContinuousTime.IntegralAdmissibility
#lint in DynamicalSystems.OptimalControl.ContinuousTime.MinimumFuel
#lint in DynamicalSystems.OptimalControl.ContinuousTime.NeedleCostIdentity
#lint in DynamicalSystems.OptimalControl.ContinuousTime.NeedleCostRemainder
#lint in DynamicalSystems.OptimalControl.ContinuousTime.NeedleFamily
#lint in DynamicalSystems.OptimalControl.ContinuousTime.NeedlePMP
#lint in DynamicalSystems.OptimalControl.ContinuousTime.NeedlePMPOnHorizon
#lint in DynamicalSystems.OptimalControl.ContinuousTime.NeedleSeparation
#lint in DynamicalSystems.OptimalControl.ContinuousTime.NeedleTerminalFamily
#lint in DynamicalSystems.OptimalControl.ContinuousTime.NeedleTrajectory
#lint in DynamicalSystems.OptimalControl.ContinuousTime.OptimalityGeometry
#lint in DynamicalSystems.OptimalControl.ContinuousTime.ReferenceExtension
#lint in DynamicalSystems.OptimalControl.ContinuousTime.TerminalNeedleSensitivity
#lint in DynamicalSystems.OptimalControl.ContinuousTime.TimeReparametrization
#lint in DynamicalSystems.OptimalControl.ContinuousTime.TimeReparametrizationFamily
#lint in DynamicalSystems.OptimalControl.ContinuousTime.UniformNeedleRemainder
#lint in DynamicalSystems.OptimalControl.ContinuousTime.UniformTaylorRemainder
#lint in DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.ClassicalAdmissibility
#lint in DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.ClassicalAdmissibilityOCP
#lint in DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.HorizonLocality
#lint in DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.QuadraticCost
#lint in DynamicalSystemsTest.KirkMedhin.NonautonomousFlowOrder
#lint in DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.NotSufficient
#lint in DynamicalSystemsTest.OptimalControl.ContinuousTime.MinimumPrinciple.PointwiseRepresentative
