import DynamicalSystems.Basic.NonAutonomous
import DynamicalSystems.Mathlib.Analysis.ODE.GlobalExistenceLinear
import DynamicalSystems.Mathlib.Analysis.ODE.NeedleDisplacement
import DynamicalSystems.Mathlib.Analysis.ODE.StateTransition
import DynamicalSystems.Mathlib.Analysis.ODE.StateTransitionExistence
import DynamicalSystems.Mathlib.Analysis.ODE.StateTransitionPiecewise
import DynamicalSystems.OptimalControl.ContinuousTime.ActualNeedleCostRemainder
import DynamicalSystems.OptimalControl.ContinuousTime.AdjointExistence
import DynamicalSystems.OptimalControl.ContinuousTime.AdjointPairing
import DynamicalSystems.OptimalControl.ContinuousTime.AugmentedCostate
import DynamicalSystems.OptimalControl.ContinuousTime.BolzaAugmentation
import DynamicalSystems.OptimalControl.ContinuousTime.ConstrainedCoVMultipliers
import DynamicalSystems.OptimalControl.ContinuousTime.CovectorPMPBridge
import DynamicalSystems.OptimalControl.ContinuousTime.DynamicProgrammingMinPrincipleFromHJB
import DynamicalSystems.OptimalControl.ContinuousTime.GeometricMinimumPrinciple
import DynamicalSystems.OptimalControl.ContinuousTime.GeometricNeedlePMP
import DynamicalSystems.OptimalControl.ContinuousTime.HJBResidualBridge
import DynamicalSystems.OptimalControl.ContinuousTime.IntegralAdmissibility
import DynamicalSystems.OptimalControl.ContinuousTime.MinimumFuel
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleCostIdentity
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleCostRemainder
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleFamily
import DynamicalSystems.OptimalControl.ContinuousTime.NeedlePMP
import DynamicalSystems.OptimalControl.ContinuousTime.NeedlePMPOnHorizon
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleSeparation
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleTerminalFamily
import DynamicalSystems.OptimalControl.ContinuousTime.NeedleTrajectory
import DynamicalSystems.OptimalControl.ContinuousTime.OptimalityGeometry
import DynamicalSystems.OptimalControl.ContinuousTime.ReferenceExtension
import DynamicalSystems.OptimalControl.ContinuousTime.TerminalNeedleSensitivity
import DynamicalSystems.OptimalControl.ContinuousTime.TimeReparametrization
import DynamicalSystems.OptimalControl.ContinuousTime.TimeReparametrizationFamily
import DynamicalSystems.OptimalControl.ContinuousTime.UniformNeedleRemainder
import DynamicalSystems.OptimalControl.ContinuousTime.UniformTaylorRemainder
import DynamicalSystemsTest.KirkMedhin.K1PointwiseObstruction
import DynamicalSystemsTest.KirkMedhin.K1ProjectCounterexample
import DynamicalSystemsTest.KirkMedhin.NeedlePMPHorizonRegression
import DynamicalSystemsTest.KirkMedhin.NeedlePMPQuadraticExample
import DynamicalSystemsTest.KirkMedhin.NonautonomousFlowOrder
import DynamicalSystemsTest.KirkMedhin.PMPNotSufficient
import DynamicalSystemsTest.KirkMedhin.PointwisePMPObstruction

/-! Kernel dependency audit for the cumulative Kirk–Medhin handoff. -/

#print axioms AutonomousFlow.toNonautonomousFlow
#print axioms HJBResidualBridge.hjb_value_gradient_adjoint
#print axioms IsoperimetricVariation.exists_firstVariation_multiplier_of_curve_family
#print axioms IsoperimetricVariation.exists_normal_multiplier
#print axioms IsoperimetricVariation.exists_normal_multiplier_apply
#print axioms IsoperimetricVariation.exists_normal_multiplier_of_curve_family
#print axioms IsoperimetricVariation.exists_normal_multipliers
#print axioms K1AdjointExistence.exists_adjointOn_Icc
#print axioms K1AdjointExistence.exists_project_costate_of_spatial_derivatives
#print axioms K1AdjointPairing.cost_difference_identity
#print axioms K1AdjointPairing.hasDerivWithinAt_pairing
#print axioms K1AdjointPairing.hasGradientAt_hamiltonian
#print axioms K1AdjointPairing.integral_adjoint_pairing
#print axioms K1CovectorPMP.projectPMP_of_covector
#print axioms K1HorizonRegression.no_global_nominal_zero_bound
#print axioms K1HorizonRegression.regularity
#print axioms K1NeedleCost.UniformSmall.tendsto_scaled_integral
#print axioms K1NeedleCost.UniformVanishing.tendsto_scaled_needle_integral
#print axioms K1NeedleCost.cost_difference_eq_impulse_add_actualRemainder
#print axioms K1NeedleCost.exists_eventually_controlIncrementError_le_linear
#print axioms K1NeedleCost.exists_uniform_increment_bound_near_reference
#print axioms K1NeedleCost.norm_remainder_le_quadratic
#print axioms K1NeedleCost.norm_taylorError_le_of_derivative_bound
#print axioms K1NeedleCost.norm_taylorError_le_quadratic
#print axioms K1NeedleCost.tendsto_scaled_actualFamilyRemainder
#print axioms K1NeedleCost.tendsto_scaled_actualFamilyRemainder_of_C1
#print axioms K1NeedleCost.tendsto_scaled_actualFamilyRemainder_of_continuous
#print axioms K1NeedleCost.tendsto_scaled_of_quadratic_bound
#print axioms K1NeedleCost.tendsto_scaled_remainder_of_uniformSmall
#print axioms K1NeedleCost.tendsto_scaled_remainder_of_uniformVanishing
#print axioms K1NeedleCost.tendsto_scaled_terminal_taylorError
#print axioms K1NeedleCost.uniformSmall_taylorError
#print axioms K1NeedleCost.uniformVanishing_controlIncrementError
#print axioms K1NeedleCost.uniform_taylorError_near_reference
#print axioms K1NeedlePMP.GlobalSmoothNeedleData.exists_costate
#print axioms K1NeedlePMP.hamiltonianMinimizing_of_positive_time_jumps
#print axioms K1NeedlePMP.needleCostate_of_globalIntegralOptimality
#print axioms K1NeedlePMP.needleCostate_of_integralOptimality_smooth
#print axioms K1NeedlePMPOnHorizon.clamped_admissible_iff
#print axioms K1NeedlePMPOnHorizon.needleCostate_of_integralOptimality_onHorizon
#print axioms K1PointwiseObstruction.reference_has_no_normal_pmp
#print axioms K1PointwiseObstruction.reference_optimal
#print axioms K1ProjectCounterexample.optimality_does_not_imply_pmp
#print axioms K1ProjectCounterexample.problem_data_smooth
#print axioms K1ProjectCounterexample.reference_isOptimalPair
#print axioms K1ProjectCounterexample.reference_no_costate
#print axioms K1ProjectCounterexample.reference_smooth
#print axioms K1QuadraticExample.explicit_costate
#print axioms K1QuadraticExample.pmp_from_general_theorem
#print axioms K1QuadraticExample.reference_optimal
#print axioms K1QuadraticExample.running_not_globally_lipschitz
#print axioms KirkMedhin.IsStateTransition.duhamel_cancellation
#print axioms KirkMedhin.IsStateTransition.terminal_covector_derivative
#print axioms KirkMedhin.IsStateTransition.variationOfConstants
#print axioms KirkMedhin.IsStateTransition.variationOfConstants_off_countable
#print axioms KirkMedhin.K1.PointwiseObstruction.optimal_without_pointwise_pmp
#print axioms KirkMedhin.K1.costAugmentedEndpoint_eq_terminal_of_admissible
#print axioms KirkMedhin.K1.exists_augmented_stateTransitionOn_Icc
#print axioms KirkMedhin.K1.exists_geometricNormalPMP_of_primitive_data
#print axioms KirkMedhin.K1.exists_needle_endpointTangent_of_primitive_data
#print axioms KirkMedhin.K1.exists_normal_augmented_terminal_covector
#print axioms KirkMedhin.K1.hahnBanach_needle_inequality
#print axioms KirkMedhin.K1.integralAdmissible_costLift
#print axioms KirkMedhin.K1.integralAdmissible_of_augmented
#print axioms KirkMedhin.K1.integralOptimal_costLift
#print axioms KirkMedhin.K1.integralOptimal_costSlope_nonneg
#print axioms KirkMedhin.K1.integralOptimal_hahnBanach_needle_inequality
#print axioms KirkMedhin.K1.integralOptimal_implies_PMP_via_hahnBanach
#print axioms KirkMedhin.K1.integralOptimal_implies_PMP_via_hahnBanach_of_integral_reference
#print axioms KirkMedhin.K1.integralOptimal_normal_covector_of_endpointTangents
#print axioms KirkMedhin.K1.nonneg_of_eventually_minimizing_costSlope
#print axioms KirkMedhin.K1.terminalCost_costSlope_of_endpointTangent_punctured
#print axioms KirkMedhin.TimeReparametrization.actualCornerCost_isLocalMin_of_ambient_min
#print axioms KirkMedhin.TimeReparametrization.actualCornerCost_isLocalMin_of_optimal_duration
#print axioms KirkMedhin.TimeReparametrization.concatenate_continuous
#print axioms KirkMedhin.TimeReparametrization.concatenate_isPiecewiseC1
#print axioms KirkMedhin.TimeReparametrization.concatenate_mem_fixedEndpointPiecewiseC1Curves
#print axioms KirkMedhin.TimeReparametrization.continuousOn_rescaledDensityDerivative
#print axioms KirkMedhin.TimeReparametrization.corner_energy_eq_of_actual_min
#print axioms KirkMedhin.TimeReparametrization.corner_energy_eq_of_cvFunctional_min
#print axioms KirkMedhin.TimeReparametrization.corner_energy_eq_of_eulerLagrange_min
#print axioms KirkMedhin.TimeReparametrization.cvFunctional_concatenate
#print axioms KirkMedhin.TimeReparametrization.cvFunctional_durationExchange
#print axioms KirkMedhin.TimeReparametrization.durationExchange_endpoints
#print axioms KirkMedhin.TimeReparametrization.durationExchange_isPiecewiseC1
#print axioms KirkMedhin.TimeReparametrization.durationExchange_mem_fixedEndpointPiecewiseC1Curves
#print axioms KirkMedhin.TimeReparametrization.durationExchange_zero
#print axioms KirkMedhin.TimeReparametrization.energy_eq_of_eulerLagrange
#print axioms KirkMedhin.TimeReparametrization.exchanged_durations
#print axioms KirkMedhin.TimeReparametrization.hasDerivAt_actualArcCost_energy
#print axioms KirkMedhin.TimeReparametrization.hasDerivAt_actualCornerCost
#print axioms KirkMedhin.TimeReparametrization.hasDerivAt_concatenate_left
#print axioms KirkMedhin.TimeReparametrization.hasDerivAt_concatenate_right
#print axioms KirkMedhin.TimeReparametrization.hasDerivAt_energy_zero
#print axioms KirkMedhin.TimeReparametrization.hasDerivAt_rescaledArc
#print axioms KirkMedhin.TimeReparametrization.hasDerivAt_rescaledArcCost
#print axioms KirkMedhin.TimeReparametrization.hasDerivAt_rescaledArcCost_energy
#print axioms KirkMedhin.TimeReparametrization.hasDerivAt_rescaledDensity
#print axioms KirkMedhin.TimeReparametrization.rescaledArcCost_eq_actual
#print axioms KirkMedhin.TimeReparametrization.rescaledDensityDerivative_one
#print axioms KirkMedhin.TimeReparametrization.rescaled_arcs_preserve_join
#print axioms KirkMedhin.TimeReparametrization.rescaling_factors_pos
#print axioms KirkMedhin.TimeReparametrization.state_fderiv_apply
#print axioms KirkMedhin.TimeReparametrization.velocity_fderiv_apply
#print axioms KirkMedhin.duhamel_cancellation_right
#print axioms KirkMedhin.exists_stateTransitionOn_Icc
#print axioms KirkMedhin.terminal_sensitivity_of_right_ODE
#print axioms KirkMedhin.terminal_tangent_of_right_ODE
#print axioms KirkMedhin.uniformSmall_clm_apply
#print axioms KirkMedhin.variationOfConstants_right_of_backward
#print axioms MinimumFuel.boxHamiltonian_eq_sum
#print axioms MinimumFuel.boxSelector_minimizes
#print axioms MinimumFuel.box_minimizer_iff_coordinate_minimizers
#print axioms MinimumFuel.box_minimizer_iff_switchingLaw
#print axioms MinimumFuel.box_one_eq_unitBox
#print axioms MinimumFuel.controlAffineHamiltonian_eq
#print axioms MinimumFuel.hamiltonianMinimizing_iff_box_minimum
#print axioms MinimumFuel.hamiltonianMinimizing_iff_switchingLaw
#print axioms MinimumFuel.scalarSelector_minimizes
#print axioms MinimumFuel.scalar_minimizer_iff_eq_lower
#print axioms MinimumFuel.scalar_minimizer_iff_eq_upper
#print axioms MinimumFuel.scalar_minimizer_iff_eq_zero
#print axioms MinimumFuel.scalar_minimizer_iff_switchingLaw
#print axioms MinimumFuel.scalar_minimizer_neg_threshold_iff
#print axioms MinimumFuel.scalar_minimizer_pos_threshold_iff
#print axioms NeedleIntegralModel.HamiltonianMinimizing_congr_state
#print axioms NeedleIntegralModel.IsIntegralAdmissiblePair.congr_state
#print axioms NeedleIntegralModel.IsIntegralAdmissiblePair.continuousOn
#print axioms NeedleIntegralModel.IsIntegralAdmissiblePair.hasDerivWithinAt
#print axioms NeedleIntegralModel.IsIntegralOptimalPair.congr_state
#print axioms NeedleIntegralModel.costateEquation_congr_state
#print axioms NeedleIntegralModel.exists_feasible_needle
#print axioms NeedleIntegralModel.exists_feasible_needle_family
#print axioms NeedleIntegralModel.exists_frozen_forcing_bound
#print axioms NeedleIntegralModel.exists_global_optimal_reference_extension
#print axioms NeedleIntegralModel.exists_global_optimal_reference_of_integral
#print axioms NeedleIntegralModel.exists_global_reference_extension
#print axioms NeedleIntegralModel.exists_spliced_solution
#print axioms NeedleIntegralModel.intervalIntegrable_needle_branches
#print axioms NeedleIntegralModel.of_classical
#print axioms NeedleIntegralModel.of_right_derivative
#print axioms NeedleIntegralModel.splice_continuous
#print axioms NeedleIntegralModel.splice_hasDerivWithinAt
#print axioms NeedleIntegralModel.terminal_tangent_of_constructed_family
#print axioms NeedleIntegralModel.totalCost_eq_of_eqOn
#print axioms NeedleIntegralModel.transversalityCondition_congr_state
#print axioms NonautonomousFlow.ext
#print axioms NonautonomousFlow.toAutonomousFlow
#print axioms NonautonomousFlowOrder.bundled_reverse
#print axioms NonautonomousFlowOrder.bundled_solves
#print axioms NonautonomousFlowOrder.cocycle
#print axioms NonautonomousFlowOrder.existsUnique_bundled_solution
#print axioms NonautonomousFlowOrder.field_continuous
#print axioms NonautonomousFlowOrder.field_lipschitz
#print axioms NonautonomousFlowOrder.field_zero_bound
#print axioms NonautonomousFlowOrder.reversed_composition_fails
#print axioms NonautonomousFlowOrder.solution_eq_bundled
#print axioms NonautonomousFlowOrder.solves_ode
#print axioms PMPNotSufficient.competitor_admissible
#print axioms PMPNotSufficient.competitor_cost
#print axioms PMPNotSufficient.pmp_does_not_imply_optimality
#print axioms PMPNotSufficient.problem_data_smooth
#print axioms PMPNotSufficient.reference_cost
#print axioms PMPNotSufficient.reference_not_optimal
#print axioms PMPNotSufficient.reference_satisfies_pmp
#print axioms existsUnique_nonAutonomousFlow
#print axioms exists_nonAutonomousFlow
#print axioms hjbCostateEquation_of_residual
#print axioms hjbPMPAssembly_of_residual
#print axioms needleTrajectoryFirstOrder
#print axioms needle_displacement_bound_after_spike
#print axioms needle_displacement_firstOrder_of_integral_solutions
#print axioms unique_nonAutonomousFlow
