/-
Copyright (c) 2026 Igor Zubrycki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Igor Zubrycki
-/
module

public import Mathlib.Data.Matrix.Basic
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Calculus.Deriv.Basic
public import Mathlib.Analysis.Calculus.Deriv.Add
public import Mathlib.Analysis.Calculus.Deriv.Mul
public import Mathlib.Analysis.Calculus.Deriv.Pow
public import Mathlib.Analysis.Calculus.Deriv.Pi
public import DynamicalSystems.Control.Backstepping.Tuning
public import DynamicalSystems.Stability.Comparison
public import DynamicalSystems.Stability.Barbalat

/-!
# Command-filtered adaptive backstepping for second-order systems

This file formalizes command-filtered adaptive backstepping for second-order
strict-feedback nonlinear systems with parametric uncertainty, following
Kabziński and Mosiołek, *Projektowanie nieliniowych układów sterowania*,
Komitet Automatyki i Robotyki PAN, Monografie tom 22, Chapter 8, Section 8.1,
pages 152–157, Theorem 8.1 and Lemma 8.1, equations (8.1)–(8.43).

## System description and command filtering

The plant is the second-order system
```
x₁' = x₂ + ϕ₁(x₁)ᵀ θ
x₂' = u + ϕ₂(x₁, x₂)ᵀ θ
```
where `θ ∈ ℝᵖ` is an unknown constant parameter vector, `ϕ₁, ϕ₂ ∈ ℝᵖ` are known
regressors, and `u` is the control input. The control objective is tracking of a
smooth reference trajectory `x_d`.

In standard backstepping, the virtual stabilizing function
`α₁ = -k₁ e_{f,1} - θ̂ᵀ ϕ₁ + x_d'` must be analytically differentiated, leading to
an explosion of algebraic complexity. Command filtering avoids this:
1. `α₁` is passed through a first-order command filter
   `z₂' = -ω₂ (z₂ - α₁)`.
2. The raw tracking errors are `e_{f,1} = x₁ - x_d` and `e_{f,2} = x₂ - z₂`.
3. To cancel the filter discrepancy `z₂ - α₁`, compensating signals `p₁, p₂`
   are generated by the linear filter
   `p₁' = -k₁ p₁ + p₂ + (z₂ - α₁)`
   `p₂' = -k₂ p₂ - p₁`.
4. The compensated tracking errors are `e_{c,1} = e_{f,1} - p₁` and
   `e_{c,2} = e_{f,2} - p₂`.
5. The feedback control `u` algebraically feeds forward the filter derivative `z₂'`:
   `u = -k₂ e_{f,2} - e_{f,1} - θ̂ᵀ ϕ₂ + z₂'`.
6. Along closed-loop trajectories, the filter errors cancel identically,
   recovering the clean skew-symmetric dynamics
   `e_{c,1}' = -k₁ e_{c,1} + e_{c,2} + ϕ₁ᵀ θ̃`
   `e_{c,2}' = -e_{c,1} - k₂ e_{c,2} + ϕ₂ᵀ θ̃`.
7. Asymptotic tracking `e_{c,1} → 0` and `e_{c,2} → 0` follows via the
   LaSalle–Yoshizawa / Barbălat bridge.

## Main definitions

* `filtered_alpha1`: stabilizing virtual control `α₁ = -k₁ e_{f,1} - θ̂ ⬝ᵥ ϕ₁ + x_d'`
  (equations 8.14 and 7.15).
* `filtered_filter_ode`: command filter vector field `z₂' = -ω₂ (z₂ - α₁)`
  (equation 8.9).
* `filtered_compensation_ode1`: first compensation filter vector field
  `p₁' = -k₁ p₁ + p₂ + (z₂ - α₁)` (equation 8.16).
* `filtered_compensation_ode2`: second compensation filter vector field
  `p₂' = -k₂ p₂ - p₁` (equation 8.34).
* `filtered_control`: feedback control with filter derivative feedforward
  `u = -k₂ e_{f,2} - e_{f,1} - θ̂ ⬝ᵥ ϕ₂ + z₂'` (equation 8.32).
* `filtered_adaptation_law`: adaptation law `θ̂' = Γ *ᵥ (e_{c,1} • ϕ₁ + e_{c,2} • ϕ₂)`
  (equation 8.39).
* `filtered_Vc`: composite quadratic Lyapunov candidate for compensated errors
  (equations 8.37 and 7.29).

## Main results

* `filtered_filter_tracking_bound`: Lemma 8.1 filter tracking error bound
  `|z₂(t) - α₁(t)| ≤ (c / ω₂) (1 - exp (-ω₂ t))` under `|α₁'(t)| ≤ c` and
  `z₂(0) = α₁(0)`.
* `filtered_filter_tracking_bound_le`: asymptotic bound `|z₂(t) - α₁(t)| ≤ c / ω₂`.
* `filtered_ec1_hasDerivAt`: closed-loop derivative of the first compensated error,
  showing exact cancellation of the filter tracking error `z₂ - α₁` (equation 8.18).
* `filtered_ec2_hasDerivAt`: closed-loop derivative of the second compensated error,
  showing exact cancellation of the feedforward `z₂'` (equation 8.24).
* `filtered_Vc_hasDerivAt`: closed-loop Lyapunov derivative identity
  `V̇_c = -k₁ e_{c,1}² - k₂ e_{c,2}²` (equation 8.40).
* `filtered_Vc_hasDerivAt_of_plant`: end-to-end Lyapunov derivative connecting
  primitive plant, filter, and compensation trajectories.
* `filtered_dissipation_tendsto_zero`: convergence of the dissipation rate
  `k₁ e_{c,1}² + k₂ e_{c,2}² → 0` via Barbălat's lemma.
* `filtered_tracking_tendsto_zero`: Theorem 8.1 asymptotic tracking convergence
  `e_{c,1}(t) → 0` and `e_{c,2}(t) → 0`.

## References

* J. Kabziński, P. Mosiołek, *Projektowanie nieliniowych układów sterowania*,
  Komitet Automatyki i Robotyki PAN, Monografie tom 22, Chapter 8, Section 8.1.
* D. Swaroop, J. K. Hedrick, P. P. Yip, J. C. Gerdes, *Dynamic surface control for
  a class of nonlinear systems*, IEEE Trans. Automat. Control, 45(10):1893–1900, 2000.
* J. A. Farrell, M. Polycarpou, M. Sharma, W. Dong, *Command filtered backstepping*,
  IEEE Trans. Automat. Control, 54(6):1391–1395, 2009.
-/

open scoped Matrix

variable {p : ℕ}

@[expose] public section

/-! ### Definitions -/

/-- Virtual control (stabilizing function) `α₁` for the command-filtered system:
`α₁ = -k₁ e_{f,1} - θ̂ ⬝ᵥ ϕ₁ + x_d'` (Kabziński–Mosiołek, equation 8.14). -/
-- The underscore in `filtered_alpha1` is mandated by the campaign's
-- required-declaration list, so the naming linter is disabled for this def.
@[nolint defsWithUnderscore]
def filtered_alpha1
    (k1 : ℝ) (ef1 : ℝ) (theta_hat phi1 : Fin p → ℝ) (xd' : ℝ) : ℝ :=
  tuning_alpha1 k1 ef1 theta_hat phi1 xd'

/-- Vector field of the first-order command filter:
`z' = -ω (z - α)` (Kabziński–Mosiołek, equation 8.9). -/
-- The underscore in `filtered_filter_ode` is mandated by the campaign's
-- required-declaration list, so the naming linter is disabled for this def.
@[nolint defsWithUnderscore]
def filtered_filter_ode (omega : ℝ) (z alpha : ℝ) : ℝ :=
  -omega * (z - alpha)

/-- Vector field of the first error-compensating signal `p₁`:
`p₁' = -k₁ p₁ + p₂ + (z₂ - α₁)` (Kabziński–Mosiołek, equation 8.16). -/
-- The underscore in `filtered_compensation_ode1` is mandated by the campaign's
-- required-declaration list, so the naming linter is disabled for this def.
@[nolint defsWithUnderscore]
def filtered_compensation_ode1
    (k1 : ℝ) (p1 p2 z2 alpha1 : ℝ) : ℝ :=
  -k1 * p1 + p2 + (z2 - alpha1)

/-- Vector field of the second error-compensating signal `p₂`:
`p₂' = -k₂ p₂ - p₁` (Kabziński–Mosiołek, equation 8.34). -/
-- The underscore in `filtered_compensation_ode2` is mandated by the campaign's
-- required-declaration list, so the naming linter is disabled for this def.
@[nolint defsWithUnderscore]
def filtered_compensation_ode2 (k2 : ℝ) (p1 p2 : ℝ) : ℝ :=
  -k2 * p2 - p1

/-- Actual feedback control `u` with filter derivative feedforward:
`u = -k₂ e_{f,2} - e_{f,1} - θ̂ ⬝ᵥ ϕ₂ + z₂'` (Kabziński–Mosiołek, equation 8.32). -/
-- The underscore in `filtered_control` is mandated by the campaign's
-- required-declaration list, so the naming linter is disabled for this def.
@[nolint defsWithUnderscore]
def filtered_control
    (k2 : ℝ) (ef1 ef2 : ℝ) (theta_hat phi2 : Fin p → ℝ) (z2_dot : ℝ) : ℝ :=
  -k2 * ef2 - ef1 - (theta_hat ⬝ᵥ phi2) + z2_dot

/-- Parameter adaptation vector field for command-filtered backstepping:
`θ̂' = Γ *ᵥ (e_{c,1} • ϕ₁ + e_{c,2} • ϕ₂)` (Kabziński–Mosiołek, equation 8.39). -/
-- The underscore in `filtered_adaptation_law` is mandated by the campaign's
-- required-declaration list, so the naming linter is disabled for this def.
@[nolint defsWithUnderscore]
def filtered_adaptation_law
    (Gamma : Matrix (Fin p) (Fin p) ℝ) (phi1 phi2 : Fin p → ℝ)
    (ec1 ec2 : ℝ) : Fin p → ℝ :=
  tuning_adaptation_law Gamma
    (tuning_tau2 (tuning_tau1 ec1 phi1) ec2 phi2)

/-- Composite quadratic Lyapunov candidate for compensated errors:
`V_c(e_{c,1}, e_{c,2}, θ̃) = (1/2) e_{c,1}² + (1/2) e_{c,2}²
  + (1/2) (θ̃ ⬝ᵥ (Γ⁻¹ *ᵥ θ̃))` (Kabziński–Mosiołek, equation 8.37). -/
-- The underscore in `filtered_Vc` is mandated by the campaign's
-- required-declaration list, so the naming linter is disabled for this def.
@[nolint defsWithUnderscore]
noncomputable def filtered_Vc
    (Gamma_inv : Matrix (Fin p) (Fin p) ℝ) (ec1 ec2 : ℝ)
    (theta_tilde : Fin p → ℝ) : ℝ :=
  tuning_V2 Gamma_inv ec1 ec2 theta_tilde

/-! ### Internal calculus and algebra helpers

The calculus and algebra helpers below follow the compact private copies used by
`DynamicalSystems.Control.Adaptive.MRAC` and
`DynamicalSystems.Control.Adaptive.RobustMRAC`. -/

/-- Derivative of the filter tracking error `β(t) = z(t) - α(t)`:
`β'(t) = -ω β(t) - α'(t)` (Kabziński–Mosiołek, equation 8.41). -/
private theorem filtered_filter_error_hasDerivAt
    {z alpha : ℝ → ℝ} {alpha' : ℝ → ℝ} {omega : ℝ} {t : ℝ}
    (hz : HasDerivAt z (filtered_filter_ode omega (z t) (alpha t)) t)
    (halpha : HasDerivAt alpha (alpha' t) t) :
    HasDerivAt (fun s ↦ z s - alpha s) (-omega * (z t - alpha t) - alpha' t) t :=
  (hz.sub halpha).congr_deriv (by simp only [filtered_filter_ode])

/-- One-sided scalar comparison estimate with zero initial condition: if `v'(t) ≤ -ω v(t) + d`
for `t ≥ 0`, `ω > 0` and `v(0) = 0`, then `v(t) ≤ (d / ω) (1 - exp (-ω t))`. -/
private theorem le_of_hasDerivAt_le_neg_mul_add_zero
    {v : ℝ → ℝ} {omega d : ℝ} (homega : 0 < omega) (hv0 : v 0 = 0)
    (hderiv : ∀ t, 0 ≤ t → HasDerivAt v (deriv v t) t)
    (hineq : ∀ t, 0 ≤ t → deriv v t ≤ -(omega * v t) + d) :
    ∀ t, 0 ≤ t → v t ≤ (d / omega) * (1 - Real.exp (-omega * t)) := by
  intro t ht
  have h := le_gronwallBound_of_hasDerivAt_le (c := omega) (d := d) homega hderiv hineq t ht
  rw [hv0, zero_mul, zero_add] at h
  exact h

/-- Algebraic cancellation identity for the first compensated error:
subtracting `p₁'` from `x₁' - x_d'` cancels the filter tracking error `z₂ - α₁`
and reorganizes terms into `-k₁ e_{c,1} + e_{c,2} + ϕ₁ᵀ (θ - θ̂)`. -/
private theorem filtered_ec1_algebra
    (k1 x1 x2 xd xd' z2 p1 p2 : ℝ) (theta theta_hat phi1 : Fin p → ℝ) :
    (x2 + (theta ⬝ᵥ phi1)) - xd' -
      filtered_compensation_ode1 k1 p1 p2 z2
        (filtered_alpha1 k1 (x1 - xd) theta_hat phi1 xd') =
      -k1 * ((x1 - xd) - p1) + ((x2 - z2) - p2) + ((theta - theta_hat) ⬝ᵥ phi1) := by
  simp only [filtered_compensation_ode1, filtered_alpha1, tuning_alpha1, sub_dotProduct]
  ring

/-- Algebraic cancellation identity for the second compensated error:
subtracting `z₂'` and `p₂'` from `x₂'` cancels the feedforward derivative `z₂'`
and reorganizes terms into `-e_{c,1} - k₂ e_{c,2} + ϕ₂ᵀ (θ - θ̂)`. -/
private theorem filtered_ec2_algebra
    (k2 x1 x2 xd z2 z2_dot p1 p2 : ℝ) (theta theta_hat phi2 : Fin p → ℝ) :
    (filtered_control k2 (x1 - xd) (x2 - z2) theta_hat phi2 z2_dot + (theta ⬝ᵥ phi2)) -
      z2_dot - filtered_compensation_ode2 k2 p1 p2 =
      -((x1 - xd) - p1) - k2 * ((x2 - z2) - p2) + ((theta - theta_hat) ⬝ᵥ phi2) := by
  simp only [filtered_control, filtered_compensation_ode2, sub_dotProduct]
  ring

/-! ### Lemma 8.1: command filter tracking bound -/

/-- Filter tracking error bound of Lemma 8.1 (Kabziński–Mosiołek, Lemma 8.1,
equations 8.41–8.42).

If the virtual control derivative is uniformly bounded by `c` (`|α'(t)| ≤ c`)
and the filter is initially aligned (`z 0 = α 0`), then the filter tracking error
`|z(t) - α(t)|` is bounded by `(c / ω) * (1 - exp (-ω * t))` for all `t ≥ 0`. -/
theorem filtered_filter_tracking_bound
    {z alpha : ℝ → ℝ} {alpha' : ℝ → ℝ} {omega c : ℝ}
    (homega : 0 < omega)
    (hz0 : z 0 = alpha 0)
    (hz_deriv : ∀ t, 0 ≤ t → HasDerivAt z (-omega * (z t - alpha t)) t)
    (halpha_deriv : ∀ t, 0 ≤ t → HasDerivAt alpha (alpha' t) t)
    (halpha_bound : ∀ t, 0 ≤ t → |alpha' t| ≤ c) :
    ∀ t, 0 ≤ t → |z t - alpha t| ≤ (c / omega) * (1 - Real.exp (-omega * t)) := by
  intro t ht
  have hβderiv : ∀ s, 0 ≤ s →
      HasDerivAt (fun r ↦ z r - alpha r) (-omega * (z s - alpha s) - alpha' s) s :=
    fun s hs ↦ filtered_filter_error_hasDerivAt (hz_deriv s hs) (halpha_deriv s hs)
  have hα'lower : ∀ s, 0 ≤ s → -c ≤ alpha' s := by
    intro s hs
    have h := halpha_bound s hs
    rw [abs_le] at h
    exact h.1
  have hα'upper : ∀ s, 0 ≤ s → alpha' s ≤ c := by
    intro s hs
    have h := halpha_bound s hs
    rw [abs_le] at h
    exact h.2
  have hβupper : z t - alpha t ≤ (c / omega) * (1 - Real.exp (-omega * t)) := by
    have hmain : (fun r ↦ z r - alpha r) t ≤
        (c / omega) * (1 - Real.exp (-omega * t)) := by
      refine le_of_hasDerivAt_le_neg_mul_add_zero (v := fun r ↦ z r - alpha r)
        (omega := omega) (d := c) homega ?_ ?_ ?_ t ht
      · simp only [hz0, sub_self]
      · intro s hs
        exact (hβderiv s hs).congr_deriv (hβderiv s hs).deriv.symm
      · intro s hs
        rw [(hβderiv s hs).deriv]
        have := hα'lower s hs
        nlinarith
    exact hmain
  have hγderiv : ∀ s, 0 ≤ s →
      HasDerivAt (fun r ↦ -(z r - alpha r)) (-omega * (-(z s - alpha s)) + alpha' s) s := by
    intro s hs
    exact ((hβderiv s hs).neg).congr_deriv (by ring)
  have hγupper : -(z t - alpha t) ≤ (c / omega) * (1 - Real.exp (-omega * t)) := by
    have hmain : (fun r ↦ -(z r - alpha r)) t ≤
        (c / omega) * (1 - Real.exp (-omega * t)) := by
      refine le_of_hasDerivAt_le_neg_mul_add_zero (v := fun r ↦ -(z r - alpha r))
        (omega := omega) (d := c) homega ?_ ?_ ?_ t ht
      · simp only [hz0, sub_self, neg_zero]
      · intro s hs
        exact (hγderiv s hs).congr_deriv (hγderiv s hs).deriv.symm
      · intro s hs
        rw [(hγderiv s hs).deriv]
        have := hα'upper s hs
        nlinarith
    exact hmain
  rw [abs_le]
  exact ⟨by linarith, hβupper⟩

/-- Filter tracking asymptotic bound of Lemma 8.1:
`|z(t) - α(t)| ≤ c / ω` for all `t ≥ 0` (Kabziński–Mosiołek, equation 8.42). -/
theorem filtered_filter_tracking_bound_le
    {z alpha : ℝ → ℝ} {alpha' : ℝ → ℝ} {omega c : ℝ}
    (homega : 0 < omega) (hc : 0 ≤ c)
    (hz0 : z 0 = alpha 0)
    (hz_deriv : ∀ t, 0 ≤ t → HasDerivAt z (-omega * (z t - alpha t)) t)
    (halpha_deriv : ∀ t, 0 ≤ t → HasDerivAt alpha (alpha' t) t)
    (halpha_bound : ∀ t, 0 ≤ t → |alpha' t| ≤ c) :
    ∀ t, 0 ≤ t → |z t - alpha t| ≤ c / omega := by
  intro t ht
  have hbound :=
    filtered_filter_tracking_bound homega hz0 hz_deriv halpha_deriv halpha_bound t ht
  have hexp : Real.exp (-omega * t) ≤ 1 := by
    have h := Real.exp_le_exp.mpr (show -omega * t ≤ 0 by nlinarith [ht, homega])
    rwa [Real.exp_zero] at h
  have hfactor : (1 : ℝ) - Real.exp (-omega * t) ≤ 1 := by
    have := Real.exp_pos (-omega * t)
    linarith
  have hcoef : 0 ≤ c / omega := div_nonneg hc homega.le
  calc |z t - alpha t| ≤ (c / omega) * (1 - Real.exp (-omega * t)) := hbound
    _ ≤ (c / omega) * 1 := mul_le_mul_of_nonneg_left hfactor hcoef
    _ = c / omega := mul_one _

/-! ### Compensated tracking error dynamics -/

/-- Closed-loop derivative of the first compensated tracking error
`e_{c,1} = (x₁ - x_d) - p₁`:
`e_{c,1}' = -k₁ e_{c,1} + e_{c,2} + ϕ₁ᵀ (θ - θ̂)` (Kabziński–Mosiołek, equation 8.18).

The filter tracking discrepancy `z₂ - α₁` entering through `x₁'` is cancelled
identically by the matching term in the compensation dynamics `p₁'`. -/
theorem filtered_ec1_hasDerivAt
    {x1 x2 xd z2 p1 p2 : ℝ → ℝ} {xd' : ℝ → ℝ}
    {theta : Fin p → ℝ} {theta_hat : ℝ → (Fin p → ℝ)}
    {phi1 : ℝ → (Fin p → ℝ)}
    {k1 : ℝ} {t : ℝ}
    (hx1 : HasDerivAt x1 (x2 t + (theta ⬝ᵥ phi1 t)) t)
    (hxd : HasDerivAt xd (xd' t) t)
    (hp1 : HasDerivAt p1 (filtered_compensation_ode1 k1 (p1 t) (p2 t) (z2 t)
      (filtered_alpha1 k1 (x1 t - xd t) (theta_hat t) (phi1 t) (xd' t))) t) :
    HasDerivAt (fun s ↦ (x1 s - xd s) - p1 s)
      (-k1 * ((x1 t - xd t) - p1 t) + ((x2 t - z2 t) - p2 t) +
        ((theta - theta_hat t) ⬝ᵥ phi1 t)) t :=
  ((hx1.sub hxd).sub hp1).congr_deriv
    (filtered_ec1_algebra k1 (x1 t) (x2 t) (xd t) (xd' t) (z2 t) (p1 t) (p2 t)
      theta (theta_hat t) (phi1 t))

/-- Closed-loop derivative of the second compensated tracking error
`e_{c,2} = (x₂ - z₂) - p₂`:
`e_{c,2}' = -e_{c,1} - k₂ e_{c,2} + ϕ₂ᵀ (θ - θ̂)` (Kabziński–Mosiołek, equation 8.24).

The filter state derivative `z₂'` in `x₂' - z₂'` is cancelled identically by the
feedforward term in the control input `u`. -/
theorem filtered_ec2_hasDerivAt
    {x1 x2 xd z2 p1 p2 : ℝ → ℝ} {z2_dot : ℝ → ℝ}
    {theta : Fin p → ℝ} {theta_hat : ℝ → (Fin p → ℝ)}
    {phi2 : ℝ → (Fin p → ℝ)}
    {k2 : ℝ} {t : ℝ}
    (hx2 : HasDerivAt x2 (filtered_control k2 (x1 t - xd t) (x2 t - z2 t)
      (theta_hat t) (phi2 t) (z2_dot t) + (theta ⬝ᵥ phi2 t)) t)
    (hz2 : HasDerivAt z2 (z2_dot t) t)
    (hp2 : HasDerivAt p2 (filtered_compensation_ode2 k2 (p1 t) (p2 t)) t) :
    HasDerivAt (fun s ↦ (x2 s - z2 s) - p2 s)
      (-((x1 t - xd t) - p1 t) - k2 * ((x2 t - z2 t) - p2 t) +
        ((theta - theta_hat t) ⬝ᵥ phi2 t)) t :=
  ((hx2.sub hz2).sub hp2).congr_deriv
    (filtered_ec2_algebra k2 (x1 t) (x2 t) (xd t) (z2 t) (z2_dot t) (p1 t) (p2 t)
      theta (theta_hat t) (phi2 t))

/-! ### Composite Lyapunov derivative identity -/

/-- Derivative of the composite Lyapunov function `filtered_Vc` along closed-loop
trajectories of the compensated error coordinates:
`V̇_c = -k₁ e_{c,1}² - k₂ e_{c,2}²` (Kabziński–Mosiołek, equation 8.40).

All filter tracking terms have vanished, and parameter adaptation cancellation
operates exactly as in nominal backstepping with tuning functions. -/
theorem filtered_Vc_hasDerivAt
    {Gamma Gamma_inv : Matrix (Fin p) (Fin p) ℝ}
    {theta : Fin p → ℝ}
    {ec1 ec2 : ℝ → ℝ} {theta_hat : ℝ → (Fin p → ℝ)}
    {phi1 phi2 : ℝ → (Fin p → ℝ)} {k1 k2 : ℝ}
    (hGamma_inv_symm : Gamma_invᵀ = Gamma_inv)
    (hGamma_inv : Gamma_inv * Gamma = 1)
    {t : ℝ}
    (hec1 : HasDerivAt ec1 (-k1 * ec1 t + ec2 t + ((theta - theta_hat t) ⬝ᵥ phi1 t)) t)
    (hec2 : HasDerivAt ec2 (-ec1 t - k2 * ec2 t + ((theta - theta_hat t) ⬝ᵥ phi2 t)) t)
    (htheta_hat : ∀ j, HasDerivAt (fun s ↦ theta_hat s j)
      ((filtered_adaptation_law Gamma (phi1 t) (phi2 t) (ec1 t) (ec2 t)) j) t) :
    HasDerivAt (fun s ↦ filtered_Vc Gamma_inv (ec1 s) (ec2 s) (theta - theta_hat s))
      (-k1 * (ec1 t) ^ 2 - k2 * (ec2 t) ^ 2) t :=
  tuning_V2_hasDerivAt hGamma_inv_symm hGamma_inv hec1 hec2 htheta_hat

/-- End-to-end Lyapunov derivative identity connecting primitive plant trajectories
`x₁, x₂`, reference `x_d`, filter state `z₂`, compensation states `p₁, p₂`, and
parameter estimate `θ̂` to `V̇_c = -k₁ e_{c,1}² - k₂ e_{c,2}²`. -/
theorem filtered_Vc_hasDerivAt_of_plant
    {Gamma Gamma_inv : Matrix (Fin p) (Fin p) ℝ}
    {theta : Fin p → ℝ}
    {x1 x2 xd z2 p1 p2 : ℝ → ℝ} {xd' z2_dot : ℝ → ℝ}
    {theta_hat : ℝ → (Fin p → ℝ)}
    {phi1 phi2 : ℝ → (Fin p → ℝ)} {k1 k2 : ℝ}
    (hGamma_inv_symm : Gamma_invᵀ = Gamma_inv)
    (hGamma_inv : Gamma_inv * Gamma = 1)
    {t : ℝ}
    (hx1 : HasDerivAt x1 (x2 t + (theta ⬝ᵥ phi1 t)) t)
    (hxd : HasDerivAt xd (xd' t) t)
    (hp1 : HasDerivAt p1 (filtered_compensation_ode1 k1 (p1 t) (p2 t) (z2 t)
      (filtered_alpha1 k1 (x1 t - xd t) (theta_hat t) (phi1 t) (xd' t))) t)
    (hx2 : HasDerivAt x2 (filtered_control k2 (x1 t - xd t) (x2 t - z2 t)
      (theta_hat t) (phi2 t) (z2_dot t) + (theta ⬝ᵥ phi2 t)) t)
    (hz2 : HasDerivAt z2 (z2_dot t) t)
    (hp2 : HasDerivAt p2 (filtered_compensation_ode2 k2 (p1 t) (p2 t)) t)
    (htheta_hat : ∀ j, HasDerivAt (fun s ↦ theta_hat s j)
      ((filtered_adaptation_law Gamma (phi1 t) (phi2 t)
        ((x1 t - xd t) - p1 t) ((x2 t - z2 t) - p2 t)) j) t) :
    HasDerivAt (fun s ↦ filtered_Vc Gamma_inv
      ((x1 s - xd s) - p1 s) ((x2 s - z2 s) - p2 s) (theta - theta_hat s))
      (-k1 * ((x1 t - xd t) - p1 t) ^ 2 - k2 * ((x2 t - z2 t) - p2 t) ^ 2) t :=
  filtered_Vc_hasDerivAt hGamma_inv_symm hGamma_inv
    (filtered_ec1_hasDerivAt hx1 hxd hp1) (filtered_ec2_hasDerivAt hx2 hz2 hp2)
    htheta_hat

/-! ### Theorem 8.1: asymptotic convergence -/

/-- Convergence of the dissipation rate `k₁ e_{c,1}² + k₂ e_{c,2}² → 0` as `t → ∞`
via the LaSalle–Yoshizawa / Barbălat bridge (Kabziński–Mosiołek, Theorem 8.1). -/
theorem filtered_dissipation_tendsto_zero
    {Gamma Gamma_inv : Matrix (Fin p) (Fin p) ℝ}
    {theta : Fin p → ℝ}
    {ec1 ec2 : ℝ → ℝ} {theta_hat : ℝ → (Fin p → ℝ)}
    {phi1 phi2 : ℝ → (Fin p → ℝ)} {k1 k2 : ℝ}
    (hGamma_inv_pd : Gamma_inv.PosDef)
    (hGamma_inv : Gamma_inv * Gamma = 1)
    (hk1 : 0 < k1) (hk2 : 0 < k2)
    (hec1 : ∀ t ≥ 0, HasDerivAt ec1 (-k1 * ec1 t + ec2 t + ((theta - theta_hat t) ⬝ᵥ phi1 t)) t)
    (hec2 : ∀ t ≥ 0, HasDerivAt ec2 (-ec1 t - k2 * ec2 t + ((theta - theta_hat t) ⬝ᵥ phi2 t)) t)
    (htheta_hat : ∀ t ≥ 0, ∀ j, HasDerivAt (fun s ↦ theta_hat s j)
      ((filtered_adaptation_law Gamma (phi1 t) (phi2 t) (ec1 t) (ec2 t)) j) t)
    (huc : UniformContinuousOn (fun t ↦ k1 * (ec1 t) ^ 2 + k2 * (ec2 t) ^ 2) (Set.Ici 0)) :
    Filter.Tendsto (fun t ↦ k1 * (ec1 t) ^ 2 + k2 * (ec2 t) ^ 2) Filter.atTop (nhds 0) :=
  tuning_dissipation_tendsto_zero hGamma_inv_pd hGamma_inv hk1 hk2 hec1 hec2 htheta_hat huc

/-- Asymptotic tracking convergence of command-filtered adaptive backstepping:
both compensated error coordinates converge to zero, `e_{c,1}(t) → 0` and
`e_{c,2}(t) → 0` as `t → ∞` (Kabziński–Mosiołek, Theorem 8.1). -/
theorem filtered_tracking_tendsto_zero
    {ec1 ec2 : ℝ → ℝ} {k1 k2 : ℝ}
    (hk1 : 0 < k1) (hk2 : 0 < k2)
    (hw : Filter.Tendsto (fun t ↦ k1 * (ec1 t) ^ 2 + k2 * (ec2 t) ^ 2) Filter.atTop (nhds 0)) :
    Filter.Tendsto ec1 Filter.atTop (nhds 0) ∧ Filter.Tendsto ec2 Filter.atTop (nhds 0) :=
  tuning_tracking_tendsto_zero hk1 hk2 hw
