/-
Copyright (c) 2026 Igor Zubrycki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Igor Zubrycki
-/
module

public import DynamicalSystems.Control.SlidingMode.LMI
public import DynamicalSystems.DiscreteTime.Comparison
public import Mathlib.Probability.Distributions.Bernoulli

/-! # Packet-loss networked discrete-time sliding-mode control

This file formalizes the deterministic core of the networked control system (NCS)
of A. Argha, S. W. Su, L. Li and H. T. Nguyen, *Advances in Discrete-Time Sliding
Mode Control: Theory and Applications*, CRC Press 2018, Chapter 4, §4.2–4.4,
printed pp. 70–78 (PDF pp. 94–102).

The measured outputs of the plant are sent to the controller over a communication
network and may be lost or delayed. The book models the communicated state with
the estimator

`x_c(k) = (1 - α(k)) x(k) + α(k) x_c(k - 1)`   (4.1), printed p. 71,

where `α(k) ∈ {0, 1}` is a packet-loss indicator: `α(k) = 1` means the packet was
lost (the controller re-uses the last available value `x_c(k - 1)`) and
`α(k) = 0` means the current measurement `x(k)` is available. Here the indicator
is encoded by a Boolean *packet-delivery schedule*: we write `α k = true` for
`α(k) = 0` (delivered) and `α k = false` for `α(k) = 1` (lost).

Applying the stochastic sliding-mode control law (4.8), printed p. 74, the
disturbance-free closed loop (4.9), printed p. 74, becomes a *switched linear
recursion* `x(k + 1) = M_{α(k)} x(k)` whose two modes are the closed-loop matrices
corresponding to a delivered and to a dropped measurement. This file handles both
the **deterministic** schedule and the **stochastic** Bernoulli channel of (4.2),
printed p. 72 (slice `d4b-stochastic`), the latter at the level of the one-step
expected-Lyapunov operator.

## Main definitions

* `dsmcPacketLossPattern`: a deterministic packet-delivery schedule `ℕ → Bool`
  (`true` = packet delivered).
* `dsmcPacketLossClosedLoop`: the switched closed-loop recursion
  `x(k + 1) = A_{α(k)} x(k)`.
* `dsmcPacketLossTrajectory`: the state trajectory generated by the recursion.
* `dsmcExpectedLyapunovOperator`: the expected Lyapunov operator
  `E_P(A₀, A₁, ᾱ) = ᾱ A₁ᵀ P A₁ + (1 - ᾱ) A₀ᵀ P A₀` of the Bernoulli packet-loss
  channel (4.2), printed p. 72.

## Main results

* `dsmc_packetLoss_uniform_factor`: a strict common Lyapunov matrix for the two
  modes yields a *uniform* contraction factor `c ∈ [0, 1)` for the quadratic form.
* `dsmc_packetLoss_dropRun_bound`: over a run of equally-moded steps the quadratic
  form is bounded by `c ^ k`, via the library's `quadForm_pow_mulVec_le`; this is
  the estimate used for a class of schedules with a bound on the number of
  consecutive dropped packets.
* `dsmc_packetLoss_eventually_bounded`: for **any** schedule, the closed loop is
  uniformly bounded and its quadratic Lyapunov energy is eventually below every
  `ε > 0`, obtained from the discrete comparison estimates
  `le_of_succ_le_mul_add` and `eventually_le_add_of_succ_le_mul_add`.
* `dsmc_packetLoss_eventually_bounded_dsmc`: the same statement specialised to
  the DSMC equivalent closed loop `dsmcEquivalentClosedLoop` as the delivered mode
  and the open loop as the dropped mode (the bridge to
  `DynamicalSystems.Control.SlidingMode.DiscreteMatrix`).
* `dsmc_meanSquare_decrease_of_bernoulli`: if `P - E_P ≻ 0` then the expected
  quadratic form strictly decreases in one step (the algebraic decrease of the
  `∆V` computation (4.12), printed p. 75).
* `dsmc_bernoulli_meanSquare_decrease`: the same one-step decrease phrased as an
  integral against `ProbabilityTheory.bernoulliMeasure`.

## Implementation notes

The matrix quadratic-form toolkit (`quadForm`, `quadForm_nonneg`, `exists_factor`,
`quadForm_pow_mulVec_le`) is reused from
`DynamicalSystems.DiscreteTime.MatrixLyapunov`; the scalar comparison bounds are
reused from `DynamicalSystems.DiscreteTime.Comparison` and
`DynamicalSystems.DiscreteTime.UltimateBoundedness`. No new quadratic form, no
discrete flow, and no continuous-time `IsHurwitz` hypothesis is introduced. The
closed-loop matrices are left abstract: the book's two operating modes are the
delivered-mode closed loop and the dropped-mode (held-measurement) dynamics, and
the statements below apply to either.

## Honest boundary

The deterministic results are trajectory results: a common discrete Lyapunov
matrix for the two modes makes arbitrary switching exponentially stable (hence
uniformly and eventually bounded). The stochastic section adds only the
**one-step** expected-Lyapunov decrease of Definition 4.1 / Lemma 4.1, printed
p. 73, and eq. (4.12), printed p. 75: if the algebraic matrix inequality
`P - E_P ≻ 0` holds then the expected quadratic form (the integral against the
Bernoulli measure of (4.2), printed p. 72) strictly decreases in one step. The
trajectory-level martingale argument, the exponential **mean-square** rate
`E{‖ξ(k)‖²} ≤ γ ρᵏ E{‖ξ(0)‖²}` of Definition 4.1, printed p. 73, and the full
block LMI (4.11) of Theorem 4.1, printed p. 75, are *not* formalized here; only
the algebraic one-step condition on which they rest is. Feasibility of the LMI is
never claimed.
-/

@[expose] public section

open Filter Matrix
open scoped Topology

variable {n : ℕ}

/-- A deterministic **packet-delivery schedule** of the networked control system:
`dsmcPacketLossPattern k = true` means that the measurement packet at time `k` is
delivered, and `false` means that it is lost or delayed, so the controller re-uses
the last available value `x_c(k - 1)`. It is the deterministic (Boolean) encoding
of the packet-loss indicator `α(k)` of A. Argha, S. W. Su, L. Li and H. T. Nguyen,
*Advances in Discrete-Time Sliding Mode Control: Theory and Applications*, CRC
Press 2018, eq. (4.2), printed p. 72 (`true` corresponds to `α(k) = 0`, i.e. a
delivered packet). -/
abbrev dsmcPacketLossPattern := ℕ → Bool

/-- The **switched closed-loop recursion** of the networked control system: given
the two closed-loop matrices bundled as `A : Bool → Matrix (Fin n) (Fin n) ℝ`
(`A true` is the delivered-mode closed loop, `A false` the dropped-mode / held
measurement dynamics), the schedule `α` and the current state `x`, one step is

`x(k + 1) = dsmcPacketLossClosedLoop A α k x = A_{α(k)} x(k)`.

This is the disturbance-free closed-loop recursion (4.9) of A. Argha, S. W. Su,
L. Li and H. T. Nguyen, *Advances in Discrete-Time Sliding Mode Control: Theory
and Applications*, CRC Press 2018, printed p. 74, with the stochastic indicator
`α(k)` replaced by the deterministic schedule `α`. -/
def dsmcPacketLossClosedLoop (A : Bool → Matrix (Fin n) (Fin n) ℝ)
    (α : dsmcPacketLossPattern) (k : ℕ) (x : Fin n → ℝ) : Fin n → ℝ :=
  A (α k) *ᵥ x

/-- The **state trajectory** generated by the packet-loss closed-loop recursion:
`dsmcPacketLossTrajectory A α x₀ 0 = x₀` and
`dsmcPacketLossTrajectory A α x₀ (k + 1) = dsmcPacketLossClosedLoop A α k
(dsmcPacketLossTrajectory A α x₀ k)`. This is the state sequence `x(k)` of the
networked closed loop (4.9), printed p. 74, for the initial condition `x₀`. -/
noncomputable def dsmcPacketLossTrajectory (A : Bool → Matrix (Fin n) (Fin n) ℝ)
    (α : dsmcPacketLossPattern) (x₀ : Fin n → ℝ) : ℕ → Fin n → ℝ :=
  fun k ↦ Nat.rec x₀ (fun j xj ↦ dsmcPacketLossClosedLoop A α j xj) k

/-- The initial value of the packet-loss trajectory (a `simp` lemma). -/
@[simp] theorem dsmcPacketLossTrajectory_zero (A : Bool → Matrix (Fin n) (Fin n) ℝ)
    (α : dsmcPacketLossPattern) (x₀ : Fin n → ℝ) :
    dsmcPacketLossTrajectory A α x₀ 0 = x₀ := rfl

/-- The recursive step of the packet-loss trajectory (a `simp` lemma). -/
@[simp] theorem dsmcPacketLossTrajectory_succ (A : Bool → Matrix (Fin n) (Fin n) ℝ)
    (α : dsmcPacketLossPattern) (x₀ : Fin n → ℝ) (k : ℕ) :
    dsmcPacketLossTrajectory A α x₀ (k + 1) =
      dsmcPacketLossClosedLoop A α k (dsmcPacketLossTrajectory A α x₀ k) := rfl

/-- A **uniform contraction factor** for the two closed-loop modes. If a single
positive-definite matrix `P` makes both matrix inequalities
`P - (A_s)ᵀ P (A_s) ≻ 0` (`s = true` delivered, `s = false` dropped) strict — the
discrete Lyapunov condition `Ω₁₁ < -ηI` of A. Argha, S. W. Su, L. Li and H. T.
Nguyen, *Advances in Discrete-Time Sliding Mode Control: Theory and Applications*,
CRC Press 2018, Theorem 4.1 and eq. (4.11), printed p. 75, in its
disturbance-free deterministic form — then there is a common factor `c ∈ [0, 1)`
with

`quadForm P (A_s *ᵥ x) ≤ c * quadForm P x`  for all `s` and all `x`.

This is `exists_factor` applied to each of the two modes and combined by taking
the maximum, so the same `c` works for an arbitrary switching schedule. The
non-degeneracy hypothesis `Nonempty (Fin n)` is the one required by the
compactness argument inside `exists_factor`. -/
theorem dsmc_packetLoss_uniform_factor {A : Bool → Matrix (Fin n) (Fin n) ℝ}
    {P : Matrix (Fin n) (Fin n) ℝ} (hP : P.PosDef) (hne : Nonempty (Fin n))
    (hLMI : ∀ s, (P - (A s)ᵀ * P * (A s)).PosDef) :
    ∃ c, 0 ≤ c ∧ c < 1 ∧ ∀ s (x : Fin n → ℝ),
      quadForm P (A s *ᵥ x) ≤ c * quadForm P x := by
  obtain ⟨c₀, hc₀0, hc₀1, h₀⟩ := exists_factor hP hP (hLMI false) hne
  obtain ⟨c₁, hc₁0, hc₁1, h₁⟩ := exists_factor hP hP (hLMI true) hne
  refine ⟨max c₀ c₁, le_max_of_le_left hc₀0, max_lt hc₀1 hc₁1, ?_⟩
  intro s x
  cases s with
  | false =>
      exact (h₀ x).trans (mul_le_mul_of_nonneg_right (le_max_left c₀ c₁)
        (quadForm_nonneg hP.posSemidef x))
  | true =>
      exact (h₁ x).trans (mul_le_mul_of_nonneg_right (le_max_right c₀ c₁)
        (quadForm_nonneg hP.posSemidef x))

/-- Over a run of steps all having the same mode `s` the packet-loss trajectory is
literally the matrix power `(A s) ^ k` applied to the initial state,
`dsmcPacketLossTrajectory A (fun _ ↦ s) x₀ k = (A s ^ k) *ᵥ x₀`. This is the
algebraic identity behind `dsmc_packetLoss_dropRun_bound` and models a block of
consecutive delivered packets (`s = true`) or of consecutive dropped packets
(`s = false`), cf. the discussion of consecutive packet losses after Remark 4.1,
printed p. 72, and the estimator (4.1) of A. Argha, S. W. Su, L. Li and H. T.
Nguyen, *Advances in Discrete-Time Sliding Mode Control: Theory and Applications*,
CRC Press 2018, printed p. 71. -/
theorem dsmcPacketLossTrajectory_const (A : Bool → Matrix (Fin n) (Fin n) ℝ) (s : Bool)
    (x₀ : Fin n → ℝ) (k : ℕ) :
    dsmcPacketLossTrajectory A (fun _ ↦ s) x₀ k = (A s ^ k) *ᵥ x₀ := by
  induction k with
  | zero => simp
  | succ k ih =>
      rw [dsmcPacketLossTrajectory_succ, ih]
      simp only [dsmcPacketLossClosedLoop, pow_succ', Matrix.mulVec_mulVec]

/-- **Bound over a run of equally-moded packets.** If one step of the mode `s`
multiplies the quadratic form by at most `c` (`c ≥ 0`), then over `k` consecutive
steps of that same mode the quadratic form is at most `c ^ k` times its initial
value. This is the packet-loss run estimate powered by the library's
`quadForm_pow_mulVec_le`; it is the building block for schedules with a bound on
the number of consecutive dropped packets (the model of Remark 4.1, printed
p. 72, and the consecutive-loss discussion surrounding eqs. (4.1)–(4.3)). -/
theorem dsmc_packetLoss_dropRun_bound {A : Bool → Matrix (Fin n) (Fin n) ℝ}
    {P : Matrix (Fin n) (Fin n) ℝ} (s : Bool) {c : ℝ} (hc : 0 ≤ c)
    (hstep : ∀ x : Fin n → ℝ, quadForm P (A s *ᵥ x) ≤ c * quadForm P x)
    (k : ℕ) (x₀ : Fin n → ℝ) :
    quadForm P (dsmcPacketLossTrajectory A (fun _ ↦ s) x₀ k) ≤ c ^ k * quadForm P x₀ := by
  rw [dsmcPacketLossTrajectory_const]
  exact quadForm_pow_mulVec_le hc hstep k x₀

/-- **Deterministic packet-loss eventual boundedness.** Suppose the two closed-loop
modes (delivered and dropped) share a common strict discrete Lyapunov matrix `P`:
`P ≻ 0` and `P - (A_s)ᵀ P (A_s) ≻ 0` for both `s`. Then for **every**
packet-delivery schedule `α`:

* the quadratic Lyapunov energy `quadForm P (x(k))` is uniformly bounded by its
  initial value `quadForm P x₀`, and
* for every `ε > 0` it is eventually at most `ε`.

The second conclusion is the `ε`-slack eventual bound delivered by
`eventually_le_add_of_succ_le_mul_add`, and the first is the affine comparison
bound `le_of_succ_le_mul_add` (both with additive constant `0`, i.e. the
homogeneous packet-loss case). This is the deterministic core of the stability
argument of Theorem 4.1 of A. Argha, S. W. Su, L. Li and H. T. Nguyen, *Advances
in Discrete-Time Sliding Mode Control: Theory and Applications*, CRC Press 2018,
printed p. 75; the stochastic expectation (4.11) and the equilibrium offset it
produces are handled in the stochastic slice. The bound holds for arbitrary
switching because the contraction factor `c ∈ [0, 1)` supplied by
`dsmc_packetLoss_uniform_factor` is common to the two modes. -/
theorem dsmc_packetLoss_eventually_bounded {A : Bool → Matrix (Fin n) (Fin n) ℝ}
    {P : Matrix (Fin n) (Fin n) ℝ} (hP : P.PosDef) (hne : Nonempty (Fin n))
    (hLMI : ∀ s, (P - (A s)ᵀ * P * (A s)).PosDef)
    (α : dsmcPacketLossPattern) (x₀ : Fin n → ℝ) :
    (∃ C, ∀ k, quadForm P (dsmcPacketLossTrajectory A α x₀ k) ≤ C) ∧
      (∀ ε > 0, ∀ᶠ k in Filter.atTop,
        quadForm P (dsmcPacketLossTrajectory A α x₀ k) ≤ ε) := by
  obtain ⟨c, hc0, hc1, hstep⟩ := dsmc_packetLoss_uniform_factor hP hne hLMI
  set v : ℕ → ℝ := fun k ↦ quadForm P (dsmcPacketLossTrajectory A α x₀ k) with hv
  have hvnonneg : ∀ k, 0 ≤ v k := fun k ↦ by
    rw [hv]
    exact quadForm_nonneg hP.posSemidef _
  have hcomp : ∀ k, v (k + 1) ≤ c * v k + 0 := by
    intro k
    rw [hv]
    simpa only [dsmcPacketLossTrajectory_succ, dsmcPacketLossClosedLoop, add_zero] using
      hstep (α k) (dsmcPacketLossTrajectory A α x₀ k)
  refine ⟨?_, ?_⟩
  · refine ⟨quadForm P x₀, fun k ↦ ?_⟩
    have hb := le_of_succ_le_mul_add hc0 hc1 hvnonneg hcomp k
    simp only [zero_mul, zero_div, add_zero] at hb
    have hpow : c ^ k ≤ 1 := pow_le_one₀ hc0 hc1.le
    have hv0 : (0 : ℝ) ≤ v 0 := hvnonneg 0
    calc v k ≤ c ^ k * v 0 := hb
      _ ≤ 1 * v 0 := by gcongr
      _ = v 0 := one_mul _
      _ = quadForm P x₀ := by rw [hv]; rfl
  · intro ε hε
    have hb := eventually_le_add_of_succ_le_mul_add hc0 hc1 hvnonneg hcomp hε
    simpa only [zero_div, zero_add] using hb

/-- **Boundedness for the DSMC equivalent-control closed loop under packet loss.**
Bridge of `dsmc_packetLoss_eventually_bounded` to the sliding-mode design of
`DynamicalSystems.Control.SlidingMode.DiscreteMatrix`: the delivered mode uses the
equivalent closed loop `dsmcEquivalentClosedLoop A B C = A - B (C B)⁻¹ C A` (the
surface `{x | C x = 0}` is then invariant, eqs. (2.7)/(2.23)), and the dropped
mode uses the open-loop matrix `A` (the held-measurement dynamics during a
dropout). If a common Lyapunov matrix `P` satisfies the two strict matrix
inequalities, then for every packet-delivery schedule the networked closed loop is
uniformly and eventually bounded, exactly as in `dsmc_packetLoss_eventually_bounded`.
Unlike the surface-invariance result `dsmcEquivalentClosedLoop_slidingVariable`, no
invertibility of `C * B` is required for the boundedness conclusion: the delivered
mode is used purely as a matrix, so its construction needs no `S B` nonsingularity.
-/
theorem dsmc_packetLoss_eventually_bounded_dsmc {A B C : Matrix (Fin n) (Fin n) ℝ}
    {P : Matrix (Fin n) (Fin n) ℝ} (hP : P.PosDef)
    (hne : Nonempty (Fin n))
    (hLMI_delivered :
      (P - (dsmcEquivalentClosedLoop A B C)ᵀ * P * dsmcEquivalentClosedLoop A B C).PosDef)
    (hLMI_dropped : (P - Aᵀ * P * A).PosDef)
    (α : dsmcPacketLossPattern) (x₀ : Fin n → ℝ) :
    (∃ D, ∀ k, quadForm P (dsmcPacketLossTrajectory
        (fun s ↦ if s then dsmcEquivalentClosedLoop A B C else A) α x₀ k) ≤ D) ∧
      (∀ ε > 0, ∀ᶠ k in Filter.atTop, quadForm P (dsmcPacketLossTrajectory
        (fun s ↦ if s then dsmcEquivalentClosedLoop A B C else A) α x₀ k) ≤ ε) := by
  have hLMI : ∀ s : Bool,
      (P - ((fun s ↦ if s then dsmcEquivalentClosedLoop A B C else A) s)ᵀ * P *
        ((fun s ↦ if s then dsmcEquivalentClosedLoop A B C else A) s)).PosDef := by
    intro s
    cases s with
    | false => simpa using hLMI_dropped
    | true => simpa using hLMI_delivered
  exact dsmc_packetLoss_eventually_bounded hP hne hLMI α x₀

/-! ## Stochastic packet loss: the one-step expected Lyapunov operator

The deterministic results above treat a fixed packet-delivery schedule. In the
networked control system the packet-loss indicator is instead the Bernoulli white
sequence `α(k)` of eq. (4.2), printed p. 72, with `Prob{α(k) = 1} = 1 - ᾱ` and
`Prob{α(k) = 0} = ᾱ` (the book's `ᾱ` is the probability of a *lost* packet; in
this file `ᾱ` is used as the **delivery** probability, i.e. as the weight of the
delivered mode `A₁`, in accordance with the task's convention).

For a Lyapunov matrix `P`, one step of the channel maps the deterministic
quadratic form `quadForm P` to the expectation

`E[quadForm P (x(k + 1)) | x(k) = x] =
   ᾱ * quadForm P (A₁ x) + (1 - ᾱ) * quadForm P (A₀ x)`,

which is the quadratic form of the **expected Lyapunov operator**
`E_P(A₀, A₁, ᾱ) = ᾱ • A₁ᵀ P A₁ + (1 - ᾱ) • A₀ᵀ P A₀` applied to `x`.
This is the algebraic core of the `∆V` computation (4.12), printed p. 75, and of
the mean-square notion of Definition 4.1 / Lemma 4.1, printed p. 73. Only this
one-step operator and its strict decrease are formalized; no trajectory-level
martingale or almost-sure convergence is claimed. -/

/-- The **expected discrete-Lyapunov operator** of the Bernoulli packet-loss
channel of A. Argha, S. W. Su, L. Li and H. T. Nguyen, *Advances in Discrete-Time
Sliding Mode Control: Theory and Applications*, CRC Press 2018, eq. (4.2),
printed p. 72, and eq. (4.12), printed p. 75:

`dsmcExpectedLyapunovOperator ᾱ A₀ A₁ P =
   ᾱ • (A₁ᵀ P A₁) + (1 - ᾱ) • (A₀ᵀ P A₀)`

Here `A₁` is the delivered-mode closed-loop matrix and `A₀` the dropped-mode
(held-measurement) matrix, and `ᾱ` is the delivery probability. Its defining
property is that the quadratic form of the operator is the one-step expected
quadratic form, `dsmcExpectedLyapunovOperator_quadForm` below. The definition
makes sense for every real `ᾱ`; the probabilistic interpretation of `ᾱ` as
a probability requires `0 ≤ ᾱ ≤ 1` and is used in the Bernoulli-measure
statement `dsmc_bernoulli_meanSquare_decrease`. -/
noncomputable def dsmcExpectedLyapunovOperator (ᾱ : ℝ)
    (A₀ A₁ P : Matrix (Fin n) (Fin n) ℝ) : Matrix (Fin n) (Fin n) ℝ :=
  ᾱ • (A₁ᵀ * P * A₁) + (1 - ᾱ) • (A₀ᵀ * P * A₀)

/-- The quadratic form is additive in the matrix (the linearity used to expand
`quadForm` of the expected Lyapunov operator). -/
theorem quadForm_add (P Q : Matrix (Fin n) (Fin n) ℝ) (x : Fin n → ℝ) :
    quadForm (P + Q) x = quadForm P x + quadForm Q x := by
  simp only [quadForm, Matrix.add_mulVec, dotProduct_add]

/-- The quadratic form is homogeneous in the matrix (the linearity used to
expand `quadForm` of the expected Lyapunov operator). -/
theorem quadForm_smul_left (r : ℝ) (P : Matrix (Fin n) (Fin n) ℝ) (x : Fin n → ℝ) :
    quadForm (r • P) x = r * quadForm P x := by
  simp only [quadForm, Matrix.smul_mulVec, dotProduct_smul, smul_eq_mul]

/-- The expected Lyapunov operator preserves matrix symmetry: if `Pᵀ = P`, then
`(dsmcExpectedLyapunovOperator ᾱ A₀ A₁ P)ᵀ = dsmcExpectedLyapunovOperator ᾱ A₀ A₁ P`. -/
theorem dsmcExpectedLyapunovOperator_transpose (ᾱ : ℝ)
    (A₀ A₁ P : Matrix (Fin n) (Fin n) ℝ) (hP : Pᵀ = P) :
    (dsmcExpectedLyapunovOperator ᾱ A₀ A₁ P)ᵀ = dsmcExpectedLyapunovOperator ᾱ A₀ A₁ P := by
  simp only [dsmcExpectedLyapunovOperator, transpose_add, transpose_smul,
    transpose_mul, transpose_transpose, hP, Matrix.mul_assoc]

/-- **The quadratic form of the expected Lyapunov operator is the one-step
expected quadratic form.** This is the algebraic identity that turns the matrix
inequality hypothesis of `dsmc_meanSquare_decrease_of_bernoulli` into a statement
about the expectation

`ᾱ * quadForm P (A₁ *ᵥ x) + (1 - ᾱ) * quadForm P (A₀ *ᵥ x)`,

using the substitution identity `quadForm_mulVec` of
`DynamicalSystems.DiscreteTime.MatrixLyapunov`. It is the scalar content of the
expectation computation (4.12), printed p. 75, of A. Argha, S. W. Su, L. Li and
H. T. Nguyen, *Advances in Discrete-Time Sliding Mode Control: Theory and
Applications*, CRC Press 2018. -/
theorem dsmcExpectedLyapunovOperator_quadForm (ᾱ : ℝ)
    (A₀ A₁ P : Matrix (Fin n) (Fin n) ℝ) (x : Fin n → ℝ) :
    quadForm (dsmcExpectedLyapunovOperator ᾱ A₀ A₁ P) x =
      ᾱ * quadForm P (A₁ *ᵥ x) + (1 - ᾱ) * quadForm P (A₀ *ᵥ x) := by
  simp only [dsmcExpectedLyapunovOperator, quadForm_add, quadForm_smul_left, quadForm_mulVec]

/-- **Purely algebraic form of the one-step strict decrease.** The convex combination
of the two one-step quadratic forms is strictly dominated by `quadForm P x` whenever
`P - dsmcExpectedLyapunovOperator ᾱ A₀ A₁ P` is positive definite, without requiring
positivity or bounds on `ᾱ`. -/
theorem dsmc_meanSquare_decrease_of_lmi (ᾱ : ℝ)
    {A₀ A₁ P : Matrix (Fin n) (Fin n) ℝ}
    (hLMI : (P - dsmcExpectedLyapunovOperator ᾱ A₀ A₁ P).PosDef)
    {x : Fin n → ℝ} (hx : x ≠ 0) :
    ᾱ * quadForm P (A₁ *ᵥ x) + (1 - ᾱ) * quadForm P (A₀ *ᵥ x) < quadForm P x := by
  have h := quadForm_pos hLMI hx
  rw [quadForm_sub, dsmcExpectedLyapunovOperator_quadForm] at h
  linarith

/-- **One-step expected mean-square decrease under Bernoulli packet loss.** If the
Lyapunov matrix `P` is positive definite and the expected Lyapunov operator
`dsmcExpectedLyapunovOperator ᾱ A₀ A₁ P` satisfies the strict matrix inequality
`P - dsmcExpectedLyapunovOperator ᾱ A₀ A₁ P ≻ 0`, then the one-step expected quadratic
form strictly decreases on every non-zero state:

`ᾱ * quadForm P (A₁ *ᵥ x) + (1 - ᾱ) * quadForm P (A₀ *ᵥ x) < quadForm P x`.

This is the algebraic one-step expected-Lyapunov condition that underlies the
`∆V < -η‖x‖²` (disturbance-free) part of Theorem 4.1 (eqs. (4.11)–(4.12),
printed p. 75) and the exponential mean-square definition of Definition 4.1,
printed p. 73, of A. Argha, S. W. Su, L. Li and H. T. Nguyen, *Advances in
Discrete-Time Sliding Mode Control: Theory and Applications*, CRC Press 2018. It
is derived from the library's strict discrete decrease `quadForm_mulVec_lt`
(`DynamicalSystems.DiscreteTime.MatrixLyapunov`) via the expectation identity
`dsmcExpectedLyapunovOperator_quadForm`: in the degenerate case `ᾱ = 1` the
condition is exactly `(P - A₁ᵀ P A₁) ≻ 0`, i.e. `quadForm_mulVec_lt` with
`M = A₁`. -/
theorem dsmc_meanSquare_decrease_of_bernoulli (ᾱ : ℝ) (hᾱ0 : 0 ≤ ᾱ) (hᾱ1 : ᾱ ≤ 1)
    {A₀ A₁ P : Matrix (Fin n) (Fin n) ℝ} (hP : P.PosDef)
    (hLMI : (P - dsmcExpectedLyapunovOperator ᾱ A₀ A₁ P).PosDef)
    {x : Fin n → ℝ} (hx : x ≠ 0) :
    ᾱ * quadForm P (A₁ *ᵥ x) + (1 - ᾱ) * quadForm P (A₀ *ᵥ x) < quadForm P x := by
  have _ := hᾱ0
  have _ := hᾱ1
  have _ := hP
  exact dsmc_meanSquare_decrease_of_lmi ᾱ hLMI hx

/-- **Mean-square nonnegativity.** For any valid Bernoulli delivery probability `ᾱ ∈ [0, 1]`
and positive semidefinite matrix `P`, the expected one-step quadratic form is nonnegative. -/
theorem dsmc_meanSquare_nonneg_of_bernoulli (ᾱ : ℝ) (hᾱ0 : 0 ≤ ᾱ) (hᾱ1 : ᾱ ≤ 1)
    {A₀ A₁ P : Matrix (Fin n) (Fin n) ℝ} (hP : P.PosSemidef) (x : Fin n → ℝ) :
    0 ≤ ᾱ * quadForm P (A₁ *ᵥ x) + (1 - ᾱ) * quadForm P (A₀ *ᵥ x) := by
  have : 0 ≤ quadForm P (A₁ *ᵥ x) := quadForm_nonneg hP _
  have : 0 ≤ quadForm P (A₀ *ᵥ x) := quadForm_nonneg hP _
  have : 0 ≤ 1 - ᾱ := sub_nonneg.mpr hᾱ1
  positivity

/-- **Mean-square decrease for DSMC equivalent-control closed loop under Bernoulli packet loss.**
Specialization of `dsmc_meanSquare_decrease_of_bernoulli` to the discrete sliding-mode closed loop
with delivered mode `dsmcEquivalentClosedLoop A B C` and dropped (held measurement) mode `A`. -/
theorem dsmc_meanSquare_decrease_of_bernoulli_dsmc (ᾱ : ℝ) (hᾱ0 : 0 ≤ ᾱ) (hᾱ1 : ᾱ ≤ 1)
    {A B C P : Matrix (Fin n) (Fin n) ℝ} (hP : P.PosDef)
    (hLMI : (P - dsmcExpectedLyapunovOperator ᾱ A (dsmcEquivalentClosedLoop A B C) P).PosDef)
    {x : Fin n → ℝ} (hx : x ≠ 0) :
    ᾱ * quadForm P (dsmcEquivalentClosedLoop A B C *ᵥ x) + (1 - ᾱ) * quadForm P (A *ᵥ x) <
      quadForm P x :=
  dsmc_meanSquare_decrease_of_bernoulli ᾱ hᾱ0 hᾱ1 hP hLMI hx

/-- The scalar expectation of a two-outcome function under the Bernoulli measure
`Ber(true, false, p)`: the `true` outcome has probability `p` and the `false`
outcome probability `1 - p`. This is `integral_bernoulliMeasure` specialised to
`Bool`-valued outcomes, used by `dsmc_bernoulli_meanSquare_decrease`. -/
private theorem integral_bernoulli_bool (p : unitInterval) (a b : ℝ) :
    ∫ s : Bool, (if s then a else b) ∂ProbabilityTheory.bernoulliMeasure true false p
      = (p : ℝ) * a + (1 - (p : ℝ)) * b := by
  rw [ProbabilityTheory.integral_bernoulliMeasure]
  simp only [smul_eq_mul, ite_true]
  rw [show (if (false = true) then a else b) = b from rfl]

/-- **One-step expected mean-square decrease as a Bernoulli integral.** The
probabilistic form of `dsmc_meanSquare_decrease_of_bernoulli`: for a delivery
probability `p : unitInterval` (`p ∈ [0, 1]`), the expected value of the per-step quadratic
form under the Bernoulli measure `bernoulliMeasure true false p` on the two
outcomes (delivered `true`, dropped `false`) strictly decreases. The expectation
is evaluated with `ProbabilityTheory.integral_bernoulliMeasure`:

`∫ b, (if b then quadForm P (A₁ x) else quadForm P (A₀ x)) ∂Ber(true, false, p)
   = p * quadForm P (A₁ x) + (1 - p) * quadForm P (A₀ x)`.

This is the measure-theoretic phrasing of the Bernoulli white sequence `α(k)` of
eq. (4.2), printed p. 72, and of the expected-Lyapunov computation (4.12),
printed p. 75, of A. Argha, S. W. Su, L. Li and H. T. Nguyen, *Advances in
Discrete-Time Sliding Mode Control: Theory and Applications*, CRC Press 2018. The
expectation is only the **one-step** conditional expectation at a deterministic
state `x`; the state itself is not modelled as a random variable here. -/
theorem dsmc_bernoulli_meanSquare_decrease {A₀ A₁ P : Matrix (Fin n) (Fin n) ℝ}
    (hP : P.PosDef) {p : unitInterval}
    (hLMI : (P - dsmcExpectedLyapunovOperator (p : ℝ) A₀ A₁ P).PosDef)
    {x : Fin n → ℝ} (hx : x ≠ 0) :
    ∫ b : Bool, (if b then quadForm P (A₁ *ᵥ x) else quadForm P (A₀ *ᵥ x))
        ∂ProbabilityTheory.bernoulliMeasure true false p < quadForm P x := by
  rw [integral_bernoulli_bool p (quadForm P (A₁ *ᵥ x)) (quadForm P (A₀ *ᵥ x))]
  exact dsmc_meanSquare_decrease_of_bernoulli (p : ℝ) p.2.1 p.2.2 hP hLMI hx
